import fs from 'fs';

let content = fs.readFileSync('src/config/site.js', 'utf8');

const newProducts = [
  {
    slug: 'philter-xpa',
    name: 'Philter XPA',
    price: 21.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Philter',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '4.2%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'XPA',
    flavourProfile: ['Tropical', 'Citrus', 'Crisp', 'Refreshing'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'XPA', 'Marrickville Sydney', 'Independent'],
    collections: ['australian-craft-beer', 'xpa', 'craft-beer'],
    seoUrl: '/beer/craft-beer/philter-xpa',
    description: 'Philter XPA is an approachable, refreshing extra pale ale brewed in Marrickville with bright tropical fruit and citrus hop characteristics.',
    shortDescription: 'Marrickville-crafted 4.2% XPA with vibrant tropical and citrus hop notes.',
    searchKeywords: 'philter xpa 375ml can 4 pack 16 pack marrickville sydney',
    badge: 'Indie Craft',
    featured: false,
    images: ['https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 21.99,
        sku: 'PHIL-XPA-375C-4PK',
        barcode: '9334455000101',
        stock: 40,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 69.99,
        sku: 'PHIL-XPA-375C-16PK',
        barcode: '9334455000118',
        stock: 20,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'mountain-culture-status-quo-pale-ale',
    name: 'Mountain Culture Status Quo Pale Ale',
    price: 23.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Mountain Culture',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '5.2%',
    containerType: 'Can',
    bottleOrCanSize: '355ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Pale Ale',
    flavourProfile: ['Juicy Mango', 'Ripe Peach', 'Citra & Mosaic Hops', 'Silky Oats'],
    dietary: ['Australian Made', 'Australian Owned', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Pale Ale', 'GABS #1 Winner', 'Craft Icon'],
    collections: ['australian-craft-beer', 'pale-ale', 'best-sellers', 'craft-beer'],
    seoUrl: '/beer/craft-beer/mountain-culture-status-quo-pale-ale',
    description: 'Brewed in the Blue Mountains by Mountain Culture Beer Co. Status Quo is Australia’s top-voted craft pale ale, double dry-hopped with Citra and Mosaic for a silky mouthfeel and explosive tropical mango, peach, and citrus aromas.',
    shortDescription: 'Blue Mountains’ award-winning 5.2% Pale Ale packed with juicy tropical stonefruit and silky oats.',
    searchKeywords: 'mountain culture status quo pale ale 355ml can 4 pack 16 pack katoomba blue mountains',
    badge: 'GABS #1 Winner',
    featured: true,
    images: ['https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '355ml-can-4-pack',
        name: '355ml Can 4 Pack',
        unitSize: '355ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 23.99,
        sku: 'MC-SQ-355C-4PK',
        barcode: '9348911000074',
        stock: 40,
        weight: '1.5kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '355ml-can-16-pack',
        name: '355ml Can 16 Pack',
        unitSize: '355ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 84.99,
        sku: 'MC-SQ-355C-16PK',
        barcode: '9348911000081',
        stock: 25,
        weight: '6.0kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'stone-wood-pacific-ale',
    name: 'Stone & Wood Pacific Ale',
    price: 20.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Stone & Wood',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '4.4%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 24 Pack / Case Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Pale Ale',
    flavourProfile: ['Tropical Fruit', 'Passionfruit', 'Galaxy Hops', 'Refreshing'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Pale Ale', 'Pacific Ale', 'Byron Bay'],
    collections: ['australian-craft-beer', 'pale-ale', 'craft-beer'],
    seoUrl: '/beer/craft-beer/stone-wood-pacific-ale',
    description: 'Inspired by the North Coast lifestyle, Stone & Wood Pacific Ale is brewed in Byron Bay with Galaxy hops, offering a cloudy, refreshing tropical fruit character.',
    shortDescription: 'Byron Bay’s iconic 4.4% Pacific Ale with luscious tropical fruit and passionfruit notes.',
    searchKeywords: 'stone wood pacific ale 375ml can 4 pack 24 pack case byron bay',
    badge: 'Iconic Ale',
    featured: true,
    images: ['https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 20.99,
        sku: 'SW-PA-375C-4PK',
        barcode: '9331002000129',
        stock: 50,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-24-pack-case',
        name: '375ml Can 24 Pack / Case',
        unitSize: '375ml',
        container: 'Can',
        packSize: '24 Pack / Case',
        price: 99.99,
        sku: 'SW-PA-375C-24PK',
        barcode: '9331002000136',
        stock: 20,
        weight: '9.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'young-henrys-newtowner-australian-pale-ale',
    name: 'Young Henrys Newtowner Australian Pale Ale',
    price: 19.99,
    primaryCategory: 'beer',
    primarySubcategory: 'hazy-beer',
    brand: 'Young Henrys',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '4.8%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 24 Pack / Case Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Pale Ale',
    flavourProfile: ['Citrus', 'Floral Hops', 'Caramel Malt', 'Balanced'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Pale Ale', 'Newtown Sydney', 'Classic'],
    collections: ['australian-craft-beer', 'pale-ale', 'craft-beer'],
    seoUrl: '/beer/craft-beer/young-henrys-newtowner-australian-pale-ale',
    description: 'Young Henrys Newtowner is an Australian pale ale inspired by Newtown, blending a rich malt backbone with refreshing floral and citrus hop characters.',
    shortDescription: 'Newtown’s 4.8% signature Australian pale ale with balanced malt and citrus hops.',
    searchKeywords: 'young henrys newtowner australian pale ale 375ml can 4 pack 24 pack case',
    badge: 'Sydney Classic',
    featured: true,
    images: ['https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 19.99,
        sku: 'YH-NEW-375C-4PK',
        barcode: '9331122000102',
        stock: 45,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-24-pack-case',
        name: '375ml Can 24 Pack / Case',
        unitSize: '375ml',
        container: 'Can',
        packSize: '24 Pack / Case',
        price: 94.99,
        sku: 'YH-NEW-375C-24PK',
        barcode: '9331122000119',
        stock: 18,
        weight: '9.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'grifter-pale-ale',
    name: 'Grifter Pale Ale',
    price: 21.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'The Grifter Brewing Co.',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '5.0%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Pale Ale',
    flavourProfile: ['Pineapple', 'Citrus', 'Resinous', 'Crisp'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Pale Ale', 'Marrickville', 'Independent'],
    collections: ['australian-craft-beer', 'pale-ale', 'craft-beer'],
    seoUrl: '/beer/craft-beer/grifter-pale-ale',
    description: 'Grifter Pale Ale is an iconic Sydney craft pale ale offering an easy-drinking balance of refreshing citrus and pine hop aromas.',
    shortDescription: 'Refreshing 5.0% pale ale packed with bright citrus and pine hop profiles.',
    searchKeywords: 'grifter pale ale 375ml can 4 pack 16 pack marrickville sydney',
    badge: 'Indie Favorite',
    featured: false,
    images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 21.99,
        sku: 'GRIF-PA-375C-4PK',
        barcode: '9350011000223',
        stock: 35,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 74.99,
        sku: 'GRIF-PA-375C-16PK',
        barcode: '9350011000230',
        stock: 15,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'akasha-hopsmith-ipa',
    name: 'Akasha Hopsmith IPA',
    price: 23.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Akasha Brewing Company',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '6.8%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'IPA',
    flavourProfile: ['Pine', 'Citrus', 'Resinous', 'Bold Hops'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'IPA', 'West Coast IPA', 'Hop Forward'],
    collections: ['australian-craft-beer', 'ipa', 'craft-beer'],
    seoUrl: '/beer/craft-beer/akasha-hopsmith-ipa',
    description: 'Akasha Hopsmith IPA is a hop-forward powerhouse loaded with resinous pine and vibrant citrus characters for true IPA enthusiasts.',
    shortDescription: 'Bold 6.8% hop-forward IPA with resinous pine and citrus aromatics.',
    searchKeywords: 'akasha hopsmith ipa 375ml can 4 pack 16 pack five dock sydney',
    badge: 'Hop Master',
    featured: false,
    images: ['https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 23.99,
        sku: 'AK-HS-375C-4PK',
        barcode: '9349888000145',
        stock: 30,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 79.99,
        sku: 'AK-HS-375C-16PK',
        barcode: '9349888000152',
        stock: 15,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'batch-brewing-co-west-coast-ipa',
    name: 'Batch Brewing Co. West Coast IPA',
    price: 23.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Batch Brewing Co.',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '6.5%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'IPA',
    flavourProfile: ['Citrus Zest', 'Pine', 'Crisp Bitterness', 'Malt Balance'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'IPA', 'West Coast IPA', 'Marrickville'],
    collections: ['australian-craft-beer', 'ipa', 'craft-beer'],
    seoUrl: '/beer/craft-beer/batch-brewing-co-west-coast-ipa',
    description: 'Batch Brewing Co. West Coast IPA delivers a classic American-style IPA profile with crisp bitterness, citrus zest, and clean pine hop flavours.',
    shortDescription: 'Classic 6.5% West Coast IPA with crisp bitterness and clean pine aromatics.',
    searchKeywords: 'batch brewing co west coast ipa 375ml can 4 pack 16 pack',
    badge: 'West Coast Style',
    featured: false,
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 23.99,
        sku: 'BATCH-WC-375C-4PK',
        barcode: '9351199000401',
        stock: 30,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 79.99,
        sku: 'BATCH-WC-375C-16PK',
        barcode: '9351199000418',
        stock: 14,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'one-drop-we-jammin-smoothie-sour',
    name: "One Drop We Jammin' Smoothie Sour",
    price: 31.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'One Drop Brewing Co.',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '6.5%',
    containerType: 'Can',
    bottleOrCanSize: '440ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Sour Beer / Specialty Beer',
    flavourProfile: ['Berry Smoothie', 'Tart Fruit', 'Vanilla', 'Creamy'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Sour Beer / Specialty Beer', 'Smoothie Sour', 'Fruit Sour'],
    collections: ['australian-craft-beer', 'sour-beer', 'craft-beer'],
    seoUrl: '/beer/craft-beer/one-drop-we-jammin-smoothie-sour',
    description: "One Drop We Jammin' is a decadent smoothie-style sour ale packed with massive quantities of fresh fruit puree and lactose for a luscious, tart, and creamy treat.",
    shortDescription: 'Decadent 6.5% fruit smoothie sour loaded with vibrant fruit purées and creamy texture.',
    searchKeywords: 'one drop we jammin smoothie sour 440ml can 4 pack 16 pack botany',
    badge: 'Smoothie Sour',
    featured: true,
    images: ['https://images.unsplash.com/photo-1582234372579-2225fa5be396?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '440ml-can-4-pack',
        name: '440ml Can 4 Pack',
        unitSize: '440ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 31.99,
        sku: 'OD-WJ-440C-4PK',
        barcode: '9352341000508',
        stock: 25,
        weight: '1.9kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1582234372579-2225fa5be396?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '440ml-can-16-pack',
        name: '440ml Can 16 Pack',
        unitSize: '440ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 114.99,
        sku: 'OD-WJ-440C-16PK',
        barcode: '9352341000515',
        stock: 10,
        weight: '7.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1582234372579-2225fa5be396?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'one-drop-hazy-ipa',
    name: 'One Drop Hazy IPA',
    price: 27.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'One Drop Brewing Co.',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '6.8%',
    containerType: 'Can',
    bottleOrCanSize: '440ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Hazy Beer',
    flavourProfile: ['Tropical Fruit', 'Citrus', 'Oats', 'Hazy'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Hazy Beer', 'New England IPA', 'Botany'],
    collections: ['australian-craft-beer', 'hazy-beer', 'ipa', 'craft-beer'],
    seoUrl: '/beer/craft-beer/one-drop-hazy-ipa',
    description: 'One Drop Hazy IPA showcases the brewery’s mastery of modern hop expression in 440ml format, offering a hazy, hop-saturated profile with tropical stone fruit aromatics.',
    shortDescription: 'Expressive 6.8% hazy IPA in 440ml tall cans loaded with juicy hop character.',
    searchKeywords: 'one drop hazy ipa 440ml can 4 pack 16 pack botany sydney',
    badge: 'Craft Favorite',
    featured: false,
    images: ['https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '440ml-can-4-pack',
        name: '440ml Can 4 Pack',
        unitSize: '440ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 27.99,
        sku: 'OD-HIPA-440C-4PK',
        barcode: '9352341000300',
        stock: 30,
        weight: '1.9kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '440ml-can-16-pack',
        name: '440ml Can 16 Pack',
        unitSize: '440ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 99.99,
        sku: 'OD-HIPA-440C-16PK',
        barcode: '9352341000317',
        stock: 15,
        weight: '7.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'mountain-culture-cult-juice-hazy-ipa',
    name: 'Mountain Culture Cult Juice Hazy IPA',
    price: 25.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Mountain Culture',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '7.0%',
    containerType: 'Can',
    bottleOrCanSize: '355ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Hazy Beer',
    flavourProfile: ['Tropical Juice', 'Passionfruit', 'Citrus', 'Resinous'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Hazy Beer', 'New England IPA', 'Craft'],
    collections: ['australian-craft-beer', 'hazy-beer', 'ipa', 'craft-beer'],
    seoUrl: '/beer/craft-beer/mountain-culture-cult-juice-hazy-ipa',
    description: 'Mountain Culture Cult Juice Hazy IPA is an ultra-juicy New England IPA loaded with heavy-hitting hop additions that deliver a smooth, velvety mouthfeel and intense tropical fruit flavours.',
    shortDescription: 'Bold 7.0% hazy IPA bursting with tropical fruit juice aromatics.',
    searchKeywords: 'mountain culture cult juice hazy ipa 355ml can 4 pack 16 pack',
    badge: 'Hazy Favorite',
    featured: true,
    images: ['https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '355ml-can-4-pack',
        name: '355ml Can 4 Pack',
        unitSize: '355ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 25.99,
        sku: 'MC-CJ-355C-4PK',
        barcode: '9348911000104',
        stock: 35,
        weight: '1.5kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '355ml-can-16-pack',
        name: '355ml Can 16 Pack',
        unitSize: '355ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 89.99,
        sku: 'MC-CJ-355C-16PK',
        barcode: '9348911000111',
        stock: 20,
        weight: '6.0kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'young-henrys-hazy-pale-ale',
    name: 'Young Henrys Hazy Pale Ale',
    price: 21.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Young Henrys',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '5.2%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Hazy Beer',
    flavourProfile: ['Tropical', 'Peach', 'Citrus', 'Balanced'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Hazy Beer', 'Newtown Sydney', 'Craft'],
    collections: ['australian-craft-beer', 'hazy-beer', 'pale-ale', 'craft-beer'],
    seoUrl: '/beer/craft-beer/young-henrys-hazy-pale-ale',
    description: 'Young Henrys Hazy Pale Ale from Newtown is an easy-drinking, fruit-forward pale ale featuring a hazy appearance and smooth tropical hop bitterness.',
    shortDescription: 'Newtown-crafted 5.2% hazy pale ale with vibrant fruit aromatics.',
    searchKeywords: 'young henrys hazy pale ale 375ml can 4 pack 16 pack newtown sydney',
    badge: 'Newtown Craft',
    featured: false,
    images: ['https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 21.99,
        sku: 'YH-HPA-375C-4PK',
        barcode: '9331122000881',
        stock: 40,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 69.99,
        sku: 'YH-HPA-375C-16PK',
        barcode: '9331122000898',
        stock: 20,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'reckless-brewing-stout',
    name: 'Reckless Brewing Stout',
    price: 22.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Reckless Brewing Co.',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '5.8%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Dark Beer & Stout',
    flavourProfile: ['Dark Chocolate', 'Espresso', 'Roasty Malt', 'Smooth'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Dark Beer & Stout', 'Stout', 'Bathurst'],
    collections: ['australian-craft-beer', 'dark-beer-stout', 'craft-beer'],
    seoUrl: '/beer/craft-beer/reckless-brewing-stout',
    description: 'Reckless Brewing Stout is a rich, roasty dark beer featuring luscious notes of dark chocolate and freshly brewed espresso with a smooth finish.',
    shortDescription: 'Rich 5.8% dark stout with robust chocolate and espresso aromatics.',
    searchKeywords: 'reckless brewing stout 375ml can 4 pack 16 pack bathurst',
    badge: 'Craft Stout',
    featured: false,
    images: ['https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 22.99,
        sku: 'RECK-ST-375C-4PK',
        barcode: '9356677000109',
        stock: 30,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 74.99,
        sku: 'RECK-ST-375C-16PK',
        barcode: '9356677000116',
        stock: 14,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1518176258769-f227c798150d?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'hawkes-patio-pale-ale',
    name: "Hawke's Patio Pale Ale",
    price: 20.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: "Hawke's Brewing Co.",
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '4.5%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Pale Ale',
    flavourProfile: ['Citrus Zest', 'Tropical Fruit', 'Crisp', 'Refreshing'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer', '100% Landfill-Free Certified'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Pale Ale', 'Marrickville', 'Sustainable'],
    collections: ['australian-craft-beer', 'pale-ale', 'craft-beer'],
    seoUrl: '/beer/craft-beer/hawkes-patio-pale-ale',
    description: "Hawke's Patio Pale Ale is a sessionable, refreshing craft pale ale brewed with vibrant citrus and tropical hop characteristics.",
    shortDescription: "Refreshing 4.5% patio pale ale with crisp citrus and tropical hop aromatics.",
    searchKeywords: 'hawkes patio pale ale 375ml can 4 pack 16 pack marrickville',
    badge: 'Sustainable Craft',
    featured: false,
    images: ['https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 20.99,
        sku: 'HAWKE-PPA-375C-4PK',
        barcode: '9347889000215',
        stock: 40,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 69.99,
        sku: 'HAWKE-PPA-375C-16PK',
        barcode: '9347889000222',
        stock: 20,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: '4-pines-japanese-lager',
    name: '4 Pines Japanese Lager',
    price: 18.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: '4 Pines',
    countryOfOrigin: 'Australia',
    regionOrState: 'New South Wales',
    abv: '4.5%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'Lager',
    flavourProfile: ['Crisp Clean', 'Subtle Rice Sweetness', 'Delicate Hops', 'Refreshing'],
    dietary: ['Australian Made', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'Lager', 'Japanese Style Lager', 'Brookvale'],
    collections: ['australian-craft-beer', 'lager', 'craft-beer'],
    seoUrl: '/beer/craft-beer/4-pines-japanese-lager',
    description: '4 Pines Japanese Lager is a crisp, ultra-refreshing lager brewed with rice for a clean, dry finish and delicate hop aroma.',
    shortDescription: 'Crisp 4.5% Japanese-style lager brewed with rice for an exceptionally clean finish.',
    searchKeywords: '4 pines japanese lager 375ml can 4 pack 16 pack brookvale',
    badge: 'Crisp Lager',
    featured: false,
    images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 18.99,
        sku: '4P-JL-375C-4PK',
        barcode: '9335566000301',
        stock: 50,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 65.99,
        sku: '4P-JL-375C-16PK',
        barcode: '9335566000318',
        stock: 22,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop'
      }
    ]
  },
  {
    slug: 'balter-xpa',
    name: 'Balter XPA',
    price: 20.99,
    primaryCategory: 'beer',
    primarySubcategory: 'craft-beer',
    brand: 'Balter Brewing Company',
    countryOfOrigin: 'Australia',
    regionOrState: 'Queensland',
    abv: '5.0%',
    containerType: 'Can',
    bottleOrCanSize: '375ml',
    packSize: '4 Pack / 16 Pack Options',
    primaryProductType: 'Craft Beer',
    styleOrVariety: 'XPA',
    flavourProfile: ['Tropical Fruit', 'Citrus', 'Pineapple', 'Smooth Finish'],
    dietary: ['Australian Made', 'Independent Craft', 'Craft Beer'],
    ageStatement: '',
    vintage: '',
    controlledTags: ['Craft Beer', 'XPA', 'Gold Coast', 'Award Winner'],
    collections: ['australian-craft-beer', 'xpa', 'best-sellers', 'craft-beer'],
    seoUrl: '/beer/craft-beer/balter-xpa',
    description: 'Balter XPA is a Gold Coast favorite that blends tropical fruit and citrus aromas with an easy-drinking, creamy mouthfeel and crisp finish.',
    shortDescription: 'Award-winning 5.0% Gold Coast XPA loaded with tropical fruit aromatics.',
    searchKeywords: 'balter xpa 375ml can 4 pack 16 pack gold coast currumbin',
    badge: 'Award Winner',
    featured: true,
    images: ['https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'],
    variants: [
      {
        id: '375ml-can-4-pack',
        name: '375ml Can 4 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '4 Pack',
        price: 20.99,
        sku: 'BALT-XPA-375C-4PK',
        barcode: '9349111000012',
        stock: 55,
        weight: '1.6kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      },
      {
        id: '375ml-can-16-pack',
        name: '375ml Can 16 Pack',
        unitSize: '375ml',
        container: 'Can',
        packSize: '16 Pack',
        price: 69.99,
        sku: 'BALT-XPA-375C-16PK',
        barcode: '9349111000029',
        stock: 24,
        weight: '6.4kg',
        availability: 'https://schema.org/InStock',
        image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?q=80&w=800&auto=format&fit=crop'
      }
    ]
  }
];

const newSlugs = newProducts.map(p => p.slug);

// Let update or insert these 15 products into PRODUCTS array in site.js
let PRODUCTS = [];
// We can evaluate or parse PRODUCTS from site.js or replace them.
// Let import PRODUCTS from site.js by dynamically or reading.
// Since we are running in node with type: module or similar, let write a script that loads site.js, updates/merges newProducts, deduplicates by slug, and rewrites site.js.
