const fs = require('fs');

const ginItems = [
  {
    name: "Gordon's London Dry Gin 700ml",
    brand: "Gordon's",
    price: 44.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "37.5%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Juniper", "Coriander", "Angelica", "Licorice"],
    desc: "Gordon's London Dry Gin is carefully distilled with a secret recipe. The distinct refreshing taste comes from its finest handpicked juniper berries and botanicals.",
    shortDesc: "World's favourite London Dry gin with crisp juniper-forward taste."
  },
  {
    name: "Gordon's London Dry Gin 1 Litre",
    brand: "Gordon's",
    price: 59.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "37.5%",
    size: "1L",
    style: "London Dry",
    botanicals: ["Juniper", "Coriander", "Angelica", "Licorice"],
    desc: "Gordon's London Dry Gin in a generous 1 Litre bottle, carefully distilled with a secret recipe of handpicked juniper berries and botanicals.",
    shortDesc: "1L value bottle of the world's favourite London Dry gin."
  },
  {
    name: "Gordon's Pink Gin 700ml",
    brand: "Gordon's",
    price: 44.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "37.5%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Raspberry", "Strawberry", "Red Currant", "Juniper"],
    desc: "Balanced to highlight the natural sweetness of raspberries and strawberries with the tang of red currant, all served up in the original Gordon's gin style.",
    shortDesc: "Refreshing pink gin infused with natural summer red berries."
  },
  {
    name: "Beefeater London Dry Gin 700ml",
    brand: "Beefeater",
    price: 49.99,
    country: "United Kingdom",
    state: "England",
    abv: "40.0%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Juniper", "Seville Orange", "Lemon Peel", "Almond", "Coriander"],
    desc: "Beefeater London Dry Gin remains faithful to James Burrough's original 19th-century recipe, featuring a bold, juniper-heavy profile with robust citrus notes.",
    shortDesc: "Iconic London Dry gin crafted in the heart of London with nine botanicals."
  },
  {
    name: "Beefeater London Dry Gin 1 Litre",
    brand: "Beefeater",
    price: 64.99,
    country: "United Kingdom",
    state: "England",
    abv: "40.0%",
    size: "1L",
    style: "London Dry",
    botanicals: ["Juniper", "Seville Orange", "Lemon Peel", "Almond", "Coriander"],
    desc: "1 Litre bottle of Beefeater London Dry Gin, featuring the classic bold juniper and citrus character inspired by the original recipe.",
    shortDesc: "1L bottle of iconic London Dry gin."
  },
  {
    name: "Beefeater Pink Strawberry Gin 700ml",
    brand: "Beefeater",
    price: 49.99,
    country: "United Kingdom",
    state: "England",
    abv: "37.5%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Strawberry", "Juniper", "Citrus"],
    desc: "A vibrant strawberry-infused gin made in London, blending natural strawberry flavor with the classic Beefeater London Dry foundation.",
    shortDesc: "Vibrant and sweet strawberry-infused pink gin."
  },
  {
    name: "Tanqueray London Dry Gin 700ml",
    brand: "Tanqueray",
    price: 54.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "40.0%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Juniper", "Coriander", "Angelica Root", "Licorice"],
    desc: "Tanqueray London Dry Gin is distilled four times for absolute purity, letting the complex, delicious blend of four classic botanicals shine through.",
    shortDesc: "Four-times distilled London Dry gin with crisp, dry botanical intensity."
  },
  {
    name: "Tanqueray London Dry Gin 1 Litre",
    brand: "Tanqueray",
    price: 69.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "40.0%",
    size: "1L",
    style: "London Dry",
    botanicals: ["Juniper", "Coriander", "Angelica Root", "Licorice"],
    desc: "1 Litre bottle of Tanqueray London Dry Gin, celebrated worldwide for its uncompromising quality and crisp juniper profile.",
    shortDesc: "1L bottle of world-renowned Tanqueray London Dry gin."
  },
  {
    name: "Tanqueray No. Ten Gin 700ml",
    brand: "Tanqueray",
    price: 74.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "47.3%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Fresh Grapefruit", "Oranges", "Limes", "Chamomile", "Juniper"],
    desc: "Tanqueray No. Ten is distilled in small batches using fresh citrus fruits, chamomile flowers, and handpicked botanicals, offering exquisite depth and elegance.",
    shortDesc: "Ultra-premium small-batch gin distilled with fresh citrus and chamomile."
  },
  {
    name: "Tanqueray Flor de Sevilla Gin 700ml",
    brand: "Tanqueray",
    price: 59.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "41.3%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Seville Oranges", "Orange Blossom", "Juniper"],
    desc: "Made with Seville oranges and orange blossoms, this flavoured gin offers a zesty, fruitful profile balanced with the four botanicals of Tanqueray's classic gin.",
    shortDesc: "Sun-soaked zesty gin crafted with sweet Seville oranges."
  },
  {
    name: "Bombay Sapphire London Dry Gin 700ml",
    brand: "Bombay Sapphire",
    price: 54.99,
    country: "United Kingdom",
    state: "England",
    abv: "40.0%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Juniper", "Lemon Peel", "Coriander", "Angelica", "Orris", "Grains of Paradise", "Cubeb Berries", "Cassia Bark", "Almond", "Licorice"],
    desc: "Vapor-infused with ten hand-selected exotic botanicals from around the world, Bombay Sapphire offers a uniquely smooth, complex taste.",
    shortDesc: "Iconic blue bottle gin vapor-infused with 10 exotic botanicals."
  },
  {
    name: "Bombay Sapphire London Dry Gin 1 Litre",
    brand: "Bombay Sapphire",
    price: 69.99,
    country: "United Kingdom",
    state: "England",
    abv: "40.0%",
    size: "1L",
    style: "London Dry",
    botanicals: ["Juniper", "Lemon Peel", "Coriander", "Angelica", "Orris", "Grains of Paradise", "Cubeb Berries", "Cassia Bark", "Almond", "Licorice"],
    desc: "1 Litre bottle of Bombay Sapphire, vapor-infused with ten exotic botanicals for a balanced, smooth flavor profile.",
    shortDesc: "1L bottle of vapor-infused Bombay Sapphire gin."
  },
  {
    name: "Bombay Sapphire Premier Cru Murcian Lemon Gin 700ml",
    brand: "Bombay Sapphire",
    price: 74.99,
    country: "United Kingdom",
    state: "England",
    abv: "47.0%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Murcian Fino Lemons", "Mandarins", "Sweet Navel Oranges", "Juniper"],
    desc: "A small-batch artisanal gin celebrating the sustainable sourcing of Fino lemons, mandarins, and sweet navel oranges from Murcia, Spain.",
    shortDesc: "Super-premium gin bursting with hand-harvested Murcian citrus."
  },
  {
    name: "Hendrick's Original Gin 700ml",
    brand: "Hendrick's",
    price: 64.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "41.4%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Bulgarian Rose Petal", "Cucumber", "Juniper", "Coriander", "Yarrow", "Elderflower"],
    desc: "Infused with Bulgarian rose and cucumber alongside traditional botanicals, Hendrick's is crafted in small batches in Ayrshire, Scotland.",
    shortDesc: "Uniquely refreshing gin infused with Bulgarian rose and crisp cucumber."
  },
  {
    name: "Hendrick's Original Gin 1 Litre",
    brand: "Hendrick's",
    price: 84.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "41.4%",
    size: "1L",
    style: "Contemporary",
    botanicals: ["Bulgarian Rose Petal", "Cucumber", "Juniper", "Coriander", "Yarrow", "Elderflower"],
    desc: "1 Litre apothecary bottle of Hendrick's Original Gin, infused with signature rose petal and cucumber extracts.",
    shortDesc: "1L bottle of iconic rose and cucumber infused gin."
  },
  {
    name: "Hendrick's Flora Adora Gin 700ml",
    brand: "Hendrick's",
    price: 79.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "43.4%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Florals for Bees", "Rose", "Cucumber", "Juniper"],
    desc: "A luscious gin inspired by the wondrous flora that lovestruck bees adore, featuring an alluringly fresh, floral bouquet.",
    shortDesc: "Limited release floral gin crafted with botanicals irresistible to bees."
  },
  {
    name: "Hendrick's Orbium Gin 700ml",
    brand: "Hendrick's",
    price: 89.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "43.4%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Quinine", "Wormwood", "Blue Lotus Blossom", "Cucumber", "Rose"],
    desc: "A peculiar gin distilled with additional extracts of quinine, wormwood, and blue lotus blossom, creating a profoundly complex, rounded flavor sphere.",
    shortDesc: "Complex limited release gin infused with blue lotus, quinine and wormwood."
  },
  {
    name: "The Botanist Islay Dry Gin 700ml",
    brand: "The Botanist",
    price: 79.99,
    country: "United Kingdom",
    state: "Scotland",
    abv: "46.0%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["22 Hand-Foraged Islay Botanicals", "Juniper", "Sweet Gale", "Thistle"],
    desc: "Crafted at Bruichladdich Distillery on Islay using 22 hand-foraged local island botanicals alongside nine classic gin aromatics.",
    shortDesc: "Artisanal Islay dry gin distilled with 22 hand-foraged island botanicals."
  },
  {
    name: "Monkey 47 Schwarzwald Dry Gin 500ml",
    brand: "Monkey 47",
    price: 99.99,
    country: "Germany",
    state: "Black Forest",
    abv: "47.0%",
    size: "500ml",
    style: "Contemporary",
    botanicals: ["47 Botanicals", "Lingonberries", "Spruce Needles", "Juniper"],
    desc: "Originating from the Black Forest in Germany, Monkey 47 combines British traditions, exotic India spices, and regional Black Forest ingredients.",
    shortDesc: "Cult-favorite complex dry gin distilled with 47 eclectic botanicals."
  },
  {
    name: "Roku Japanese Craft Gin 700ml",
    brand: "Roku",
    price: 64.99,
    country: "Japan",
    state: "Osaka",
    abv: "43.0%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Sakura Flower", "Sakura Leaf", "Sencha Tea", "Gyokuro Tea", "Sansho Pepper", "Yuzu"],
    desc: "Roku translates to 'six' in Japanese, representing six quintessential Japanese botanicals harvested across four seasons, balanced with traditional gin aromatics.",
    shortDesc: "Harmonious Japanese craft gin infused with six seasonal botanicals."
  },
  {
    name: "Nikka Coffey Gin 700ml",
    brand: "Nikka",
    price: 79.99,
    country: "Japan",
    state: "Miyagi",
    abv: "47.0%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Amanatsu", "Kabosu", "Hirado Buntan", "Shekwasha", "Sansho Pepper", "Juniper"],
    desc: "Distilled using Nikka's vintage Coffey stills, this silky gin delivers an astonishingly smooth texture and vibrant Japanese citrus aromatics.",
    shortDesc: "Silky textured Japanese gin highlighted by rare domestic citrus fruits."
  },
  {
    name: "KI NO BI Kyoto Dry Gin 700ml",
    brand: "KI NO BI",
    price: 109.99,
    country: "Japan",
    state: "Kyoto",
    abv: "45.7%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Yellow Yuzu", "Hinoki Wood", "Bamboo", "Gyokuro Green Tea", "Sansho Pepper"],
    desc: "The first dry gin from Kyoto, crafted with Japanese botanicals like yellow yuzu, hinoki wood, bamboo, and gyokuro green tea from Uji.",
    shortDesc: "Luxurious Kyoto dry gin crafted with Japanese teas, yuzu and hinoki."
  },
  {
    name: "Gin Mare Mediterranean Gin 700ml",
    brand: "Gin Mare",
    price: 79.99,
    country: "Spain",
    state: "Costa Dorada",
    abv: "42.7%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Arbequina Olives", "Thyme", "Basil", "Rosemary", "Sweet Oranges", "Juniper"],
    desc: "Capturing the spirit of the Mediterranean, Gin Mare incorporates Arbequina olives, thyme, basil, and rosemary into a savory, herbaceous botanical blend.",
    shortDesc: "Savory Mediterranean gin distilled with Arbequina olives, thyme and basil."
  },
  {
    name: "Malfy Originale Gin 700ml",
    brand: "Malfy",
    price: 59.99,
    country: "Italy",
    state: "Moncalieri",
    abv: "41.0%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Italian Juniper", "Mountain Spring Water", "Coastal Botanicals"],
    desc: "A classic Italian London Dry gin crafted with wild Italian juniper and pristine spring water from the foot of Mount Monviso.",
    shortDesc: "Crisp Italian London Dry gin inspired by coastal Italian heritage."
  },
  {
    name: "Malfy Con Limone Gin 700ml",
    brand: "Malfy",
    price: 59.99,
    country: "Italy",
    state: "Moncalieri",
    abv: "41.0%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Amalfi Lemons", "Italian Juniper", "Lemon Peel"],
    desc: "Infused with sun-ripened Amalfi coastal lemons, this zesty gin brings vibrant Italian sunshine to every glass.",
    shortDesc: "Zesty Italian gin infused with hand-picked Amalfi lemons."
  },
  {
    name: "Malfy Gin Rosa 700ml",
    brand: "Malfy",
    price: 59.99,
    country: "Italy",
    state: "Moncalieri",
    abv: "41.0%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Sicilian Pink Grapefruits", "Rhubarb", "Italian Juniper"],
    desc: "A delightful pink gin featuring Sicilian pink grapefruits and crisp rhubarb combined with Italian juniper.",
    shortDesc: "Refreshing pink gin bursting with Sicilian pink grapefruit and rhubarb."
  },
  {
    name: "Aviation American Gin 700ml",
    brand: "Aviation",
    price: 69.99,
    country: "United States",
    state: "Oregon",
    abv: "42.0%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Cardamom", "Coriander", "French Lavender", "Anise Seed", "Sarsaparilla", "Juniper"],
    desc: "Pioneering the American dry gin style, Aviation features a smoother, more floral profile where juniper takes a back seat to spice and lavender.",
    shortDesc: "Smooth American craft gin with subtle floral spice and lavender notes."
  },
  {
    name: "Sipsmith London Dry Gin 700ml",
    brand: "Sipsmith",
    price: 69.99,
    country: "United Kingdom",
    state: "England",
    abv: "41.6%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Macedonian Juniper", "Spanish Orange Peel", "Ground Almond", "Cassia Bark"],
    desc: "Handcrafted in small batches in West London, Sipsmith resurrects traditional copper pot distillation to create an impeccably balanced London Dry.",
    shortDesc: "Handcrafted small-batch London Dry gin of exceptional balance."
  },
  {
    name: "Plymouth Original Gin 700ml",
    brand: "Plymouth Gin",
    price: 59.99,
    country: "United Kingdom",
    state: "England",
    abv: "41.2%",
    size: "700ml",
    style: "London Dry",
    botanicals: ["Sweet Orange Peel", "Juniper", "Coriander Seed", "Cardamom", "Orris Root"],
    desc: "Distilled continuously at the historic Black Friars Distillery in Plymouth since 1793, featuring a uniquely earthy, fruit-forward smoothness.",
    shortDesc: "Historic, smoother-style English gin distilled continuously since 1793."
  },
  {
    name: "Four Pillars Rare Dry Gin 700ml",
    brand: "Four Pillars",
    price: 74.99,
    country: "Australia",
    state: "Victoria",
    abv: "41.8%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Tasmanian Pepperberry Leaf", "Whole Oranges", "Lemon Myrtle", "Cinnamon", "Star Anise"],
    desc: "Four Pillars Rare Dry Gin uses whole Australian oranges and native Tasmanian pepperberry leaf to deliver a spicy, citrus-forward modern Australian classic.",
    shortDesc: "Award-winning Australian dry gin featuring whole oranges and native pepperberry."
  },
  {
    name: "Four Pillars Bloody Shiraz Gin 700ml",
    brand: "Four Pillars",
    price: 79.99,
    country: "Australia",
    state: "Victoria",
    abv: "37.8%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Yarra Valley Shiraz Grapes", "Rare Dry Gin Botanicals", "Spice"],
    desc: "Yarra Valley Shiraz grapes are steeped in Rare Dry Gin for eight weeks, resulting in a luscious, ruby-red gin with sweet raspberry fruit character.",
    shortDesc: "Cult-classic Australian Shiraz gin steeped with fresh Yarra Valley grapes."
  },
  {
    name: "Four Pillars Fresh Yuzu Gin 700ml",
    brand: "Four Pillars",
    price: 79.99,
    country: "Australia",
    state: "Victoria",
    abv: "41.8%",
    size: "700ml",
    style: "Contemporary",
    botanicals: ["Australian-Grown Yuzu", "Lemon Myrtle", "Finger Lime", "Juniper"],
    desc: "Showcasing enormous aromatic citrus complexity using fresh Australian-grown yuzu and lemon myrtle.",
    shortDesc: "Vibrant citrus gin bursting with fresh Australian yuzu and native aromatics."
  },
  {
    name: "Four Pillars Spiced Negroni Gin 700ml",
    brand: "Four Pillars",
    price: 79.99,
    country: "Australia",
    state: "Victoria",
    abv: "58.8%",
    size: "700ml",
    style: "Navy Strength",
    botanicals: ["Tasmanian Pepperberry Leaf", "Grains of Paradise", "Ginger", "Orange", "Cinnamon"],
    desc: "Specifically crafted to cut through sweet vermouth and bitters in a Negroni, featuring high proof and rich, aromatic spices.",
    shortDesc: "Deeply spiced, high-proof gin purpose-built for the ultimate Negroni."
  },
  {
    name: "Four Pillars Navy Strength Gin 700ml",
    brand: "Four Pillars",
    price: 89.99,
    country: "Australia",
    state: "Victoria",
    abv: "58.8%",
    size: "700ml",
    style: "Navy Strength",
    botanicals: ["Organic Finger Limes", "Ginger", "Juniper", "Tasmanian Pepperberry"],
    desc: "A powerhouse navy strength gin featuring organic finger limes for aromatic zing and explosive intensity.",
    shortDesc: "Intense 58.8% navy strength gin featuring fresh finger limes."
  },
  {
    name: "Four Pillars Olive Leaf Gin 700ml",
    brand: "Four Pillars",
    price: 79.99,
    country: "Australia",
    state: "Victoria",
    abv: "43.8%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Olive Leaf", "Olive Oil", "Rosemary", "Thyme", "Bay Leaf", "Macadamia Nut"],
    desc: "A savory masterpiece incorporating three types of estate-grown olive leaves, extra virgin olive oil, rosemary, and macadamia nuts.",
    shortDesc: "Savory botanical gin crafted with Victorian olive leaves and macadamias."
  },
  {
    name: "Archie Rose Signature Dry Gin 700ml",
    brand: "Archie Rose",
    price: 79.99,
    country: "Australia",
    state: "New South Wales",
    abv: "42.0%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Native River Mint", "Lemon Myrtle", "Strawberry Gum", "Blood Lime", "Dorrigo Pepper"],
    desc: "Distilled in Sydney using individually distilled native botanicals including lemon myrtle, blood lime, and native river mint.",
    shortDesc: "Signature Sydney dry gin showcasing hand-selected Australian native botanicals."
  },
  {
    name: "Archie Rose Distiller's Strength Gin 700ml",
    brand: "Archie Rose",
    price: 89.99,
    country: "Australia",
    state: "New South Wales",
    abv: "52.4%",
    size: "700ml",
    style: "Navy Strength",
    botanicals: ["Double-Infused Native Botanicals", "Juniper", "Lemon Myrtle", "Pepperberry"],
    desc: "A bold, higher-proof expression of Archie Rose's signature gin, heavily double-infused with native botanicals for deep aromatic persistence.",
    shortDesc: "Punchy 52.4% distiller's strength gin with intense native botanicals."
  },
  {
    name: "Archie Rose Raspberry Aperitif Gin 700ml",
    brand: "Archie Rose",
    price: 79.99,
    country: "Australia",
    state: "New South Wales",
    abv: "22.0%",
    size: "700ml",
    style: "Aperitif Gin",
    botanicals: ["Fresh Raspberries", "Davidson Plums", "Signature Dry Gin Base"],
    desc: "A luscious ruby-hued aperitif gin marrying fresh raspberries and tart Davidson plums with Archie Rose dry gin.",
    shortDesc: "Delightful Australian aperitif gin infused with fresh raspberries and Davidson plum."
  },
  {
    name: "Never Never Triple Juniper Gin 500ml",
    brand: "Never Never Distilling Co.",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "41.0%",
    size: "500ml",
    style: "London Dry",
    botanicals: ["Triple Juniper Infusion", "Coriander Seed", "Angelica Root", "Lemon Peel"],
    desc: "A relentless pursuit of juniper perfection, utilizing a triple-stage infusion process to deliver the most juniper-forward gin in Australia.",
    shortDesc: "Award-winning bold gin crafted using a unique triple juniper process."
  },
  {
    name: "Never Never Oyster Shell Gin 500ml",
    brand: "Never Never Distilling Co.",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "41.0%",
    size: "500ml",
    style: "Contemporary",
    botanicals: ["Pacific Oyster Shells", "Saltbush", "Coastal Succulents", "Juniper"],
    desc: "Created in collaboration with Fino Seppeltsfield, utilizing pristine Pacific oyster shells and coastal saltbush to impart briny, savory complexity.",
    shortDesc: "Briny coastal gin distilled with fresh oyster shells and saltbush."
  },
  {
    name: "Never Never Juniper Freak Gin 500ml",
    brand: "Never Never Distilling Co.",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "58.0%",
    size: "500ml",
    style: "Navy Strength",
    botanicals: ["Hyper-Concentrated Juniper", "Pine Needles", "Citrus"],
    desc: "An unapologetic celebration of juniper featuring a massive, hyper-concentrated botanical load that packs an incredible aromatic punch.",
    shortDesc: "High-proof cult release loaded with hyper-concentrated juniper oils."
  },
  {
    name: "Brookie's Byron Dry Gin 700ml",
    brand: "Brookie's",
    price: 74.99,
    country: "Australia",
    state: "New South Wales",
    abv: "46.0%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["26 Botanicals", "Davidson Plum", "Lemon Aspen", "Aniseed Myrtle"],
    desc: "Distilled at the Cape Byron Distillery using 26 botanicals, 18 of which are native to the surrounding subtropical rainforest.",
    shortDesc: "Subtropical rainforest gin crafted with 18 native botanicals from Byron Bay."
  },
  {
    name: "Brookie's Byron Slow Gin 700ml",
    brand: "Brookie's",
    price: 74.99,
    country: "Australia",
    state: "New South Wales",
    abv: "26.0%",
    size: "700ml",
    style: "Sloie Gin",
    botanicals: ["Native Davidson Plums", "Brookie's Dry Gin"],
    desc: "An Australian take on traditional sloe gin, steeping wild-harvested native Davidson plums in Brookie's Dry Gin for months.",
    shortDesc: "Delicious Australian slow gin infused with native Davidson plums."
  },
  {
    name: "Manly Spirits Australian Dry Gin 700ml",
    brand: "Manly Spirits Co.",
    price: 79.99,
    country: "Australia",
    state: "New South Wales",
    abv: "43.0%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Marine Botanicals", "Sea Kelp", "Mountain Pepperleaf", "Finger Lime"],
    desc: "Inspired by the rugged marine coastline of Manly, combining sustainably harvested sea kelp with native Australian coastal botanicals.",
    shortDesc: "Coastal Australian dry gin infused with marine kelp and native citrus."
  },
  {
    name: "Manly Spirits Lilly Pilly Pink Gin 700ml",
    brand: "Manly Spirits Co.",
    price: 79.99,
    country: "Australia",
    state: "New South Wales",
    abv: "40.0%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Lilly Pilly Berries", "Raspberry", "Hibiscus", "Coastal Botanicals"],
    desc: "A shimmering pink gin flavored with wild-foraged lilly pilly berries, raspberries, and hibiscus flowers.",
    shortDesc: "Vibrant pink gin featuring native lilly pilly berries and raspberries."
  },
  {
    name: "Poor Toms Sydney Dry Gin 700ml",
    brand: "Poor Toms",
    price: 74.99,
    country: "Australia",
    state: "New South Wales",
    abv: "41.3%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Strawberry Gum", "Chamomile", "Lemon Myrtle", "Fresh Apple", "Juniper"],
    desc: "A brilliantly floral and fruit-forward Sydney dry gin featuring fresh green apple, strawberry gum, and delicate chamomile.",
    shortDesc: "Uniquely floral Sydney dry gin with fresh green apple and strawberry gum."
  },
  {
    name: "Poor Toms Strawberry Gin 700ml",
    brand: "Poor Toms",
    price: 74.99,
    country: "Australia",
    state: "New South Wales",
    abv: "40.0%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Fresh Strawberries", "Hibiscus", "Native Pepperberry", "Juniper"],
    desc: "Tasting like pure summer in a glass, this pink gin is saturated with fresh Australian strawberries and hibiscus flowers.",
    shortDesc: "Summer-fresh pink gin bursting with real strawberries and hibiscus."
  },
  {
    name: "Prohibition Original Gin 700ml",
    brand: "Prohibition Liquor Co.",
    price: 74.99,
    country: "Australia",
    state: "South Australia",
    abv: "42.0%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Native Blood Lime", "Green Tea", "Lavender", "Pink Peppercorn", "Juniper"],
    desc: "An award-winning artisanal gin crafted in Adelaide with meticulous attention to detail, featuring blood lime, green tea, and delicate lavender.",
    shortDesc: "Multi-award winning artisanal Australian dry gin with exquisite balance."
  },
  {
    name: "Prohibition Shiraz Gin 700ml",
    brand: "Prohibition Liquor Co.",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "40.0%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Barossa Shiraz Grapes", "Original Gin Botanicals", "Spices"],
    desc: "Hand-picked Barossa Valley Shiraz grapes steeped in award-winning Original Gin for a luscious, fruit-forward winter warmer.",
    shortDesc: "Luxurious Shiraz gin steeped with premium Barossa Valley grapes."
  },
  {
    name: "Applewood Coral Gin 700ml",
    brand: "Applewood Distillery",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "43.0%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Ruby Grapefruit", "Quandong", "Strawberry Gum", "Hibiscus", "Juniper"],
    desc: "A vibrant, ruby-colored gin celebrating Australian native fruits including quandong, ruby grapefruit, and strawberry gum.",
    shortDesc: "Botanical pink gin highlighting unique Australian desert fruits."
  },
  {
    name: "Applewood Okar Amaro Gin 700ml",
    brand: "Applewood Distillery",
    price: 79.99,
    country: "Australia",
    state: "South Australia",
    abv: "24.0%",
    size: "700ml",
    style: "Aperitif Gin",
    botanicals: ["Native River Mint", "Wild Citrus", "Gentian Root", "Australian Botanicals"],
    desc: "An Australian bitter aperitif gin blending native river mint, gentian root, and wild citrus for a complex bittersweet flavor profile.",
    shortDesc: "Bittersweet Australian aperitif gin crafted with native botanicals."
  },
  {
    name: "23rd Street Violet Gin 700ml",
    brand: "23rd Street Distillery",
    price: 69.99,
    country: "Australia",
    state: "South Australia",
    abv: "40.0%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Lavender", "Violet Flower Petals", "Juniper", "Citrus"],
    desc: "Infused with fragrant violet petals and lavender, offering a mesmerizing floral aroma and striking pastel hue.",
    shortDesc: "Fragrant floral gin infused with violet petals and lavender."
  },
  {
    name: "Wild Brumby Schnapps Distillery Pink Lady Gin 700ml",
    brand: "Wild Brumby",
    price: 79.99,
    country: "Australia",
    state: "New South Wales",
    abv: "40.0%",
    size: "700ml",
    style: "Pink Gin",
    botanicals: ["Pink Lady Apples", "Mountain Berries", "Juniper"],
    desc: "Distilled in the Snowy Mountains using locally grown Pink Lady apples and alpine mountain berries for a crisp, fruit-forward gin.",
    shortDesc: "Alpine pink gin distilled with fresh Snowy Mountains Pink Lady apples."
  },
  {
    name: "McHenry Classic Dry Gin 700ml",
    brand: "McHenry Distillery",
    price: 79.99,
    country: "Australia",
    state: "Tasmania",
    abv: "40.0%",
    size: "700ml",
    style: "Australian Dry",
    botanicals: ["Tasmanian Spring Water", "Pure Juniper", "Citrus Zest"],
    desc: "Crafted at Australia's southernmost distillery in Tasmania, utilizing pristine mountain spring water and classic dry gin botanicals.",
    shortDesc: "Pristine Tasmanian dry gin distilled with pure mountain spring water."
  },
  {
    name: "McHenry Butterfly Gin 700ml",
    brand: "McHenry Distillery",
    price: 79.99,
    country: "Australia",
    state: "Tasmania",
    abv: "40.0%",
    size: "700ml",
    style: "Flavoured Gin",
    botanicals: ["Butterfly Pea Flower", "Juniper", "Citrus"],
    desc: "Infused with butterfly pea flower, this enchanting gin transforms from deep blue to vibrant pink when tonic water or citrus is added.",
    shortDesc: "Magical color-changing Tasmanian gin infused with butterfly pea flower."
  }
];

const siteContent = fs.readFileSync('src/config/site.js', 'utf8');

const newProductsCode = ginItems.map((g, idx) => {
  const slug = g.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const styleSlug = g.style.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `  {
    slug: "${slug}",
    name: "${g.name}",
    price: ${g.price},
    primaryCategory: "spirits",
    primarySubcategory: "gin",
    brand: "${g.brand}",
    countryOfOrigin: "${g.country}",
    regionOrState: "${g.state}",
    abv: "${g.abv}",
    containerType: "Bottle",
    bottleOrCanSize: "${g.size}",
    packSize: "Single",
    primaryProductType: "Gin",
    styleOrVariety: "${g.style}",
    flavourProfile: ${JSON.stringify(g.botanicals)},
    dietary: [],
    ageStatement: "",
    vintage: "",
    controlledTags: ["Premium Pick", "Botanical"],
    collections: ["spirits", "gin", "${styleSlug}"],
    seoUrl: "/spirits/gin/${slug}",
    description: "${g.desc}",
    shortDescription: "${g.shortDesc}",
    searchKeywords: "${g.name.toLowerCase()}; gin; ${g.style.toLowerCase()}; ${g.brand.toLowerCase()}; ${g.country.toLowerCase()}",
    badge: "${g.style}",
    featured: ${idx < 6 ? 'true' : 'false'},
    images: ["https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop",
    category: "spirits"
  }`;
}).join(',\n\n');

// Find the closing bracket of PRODUCTS before export const POSTS = [
const targetStr = 'export const POSTS = [';
const targetIdx = siteContent.indexOf(targetStr);
if (targetIdx === -1) {
  console.error("Could not find export const POSTS in site.js");
  process.exit(1);
}

// Find the last ]; before targetIdx
const sliceBeforePosts = siteContent.slice(0, targetIdx);
const lastClosingBracketIdx = sliceBeforePosts.lastIndexOf('];');
if (lastClosingBracketIdx === -1) {
  console.error("Could not find closing bracket of PRODUCTS array");
  process.exit(1);
}

// First, clean up any previous bad insertion if present (revert site.js conceptually or search/replace)
// Since we want to be robust, let's read the original site.js or clean up. Let's do a node script that re-initializes or cleans site.js first.
console.log("Script ready.");
