import fs from 'fs';

export const RUM_PRODUCTS = [
  // --- AUSTRALIAN RUM (QUEENSLAND & NSW CRAFT) ---
  {
    name: "Bundaberg UP Original Rum 700ml",
    brand: "Bundaberg Rum",
    price: 46.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "37.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Dark Rum",
    style: "Australian Dark Rum; Cane Molasses",
    flavourProfile: ["Caramel", "Molasses", "Toasted Oak", "Golden Syrup"],
    desc: "Bundaberg Underproof (UP) Rum is an Australian icon, distilled from 100% Queensland sugar cane molasses and aged for a minimum of two years in rich American white oak vats handcrafted in Bundaberg.",
    shortDesc: "Iconic Australian dark rum aged in American oak vats with rich notes of molasses and caramel.",
    badge: "Aussie Icon",
    featured: true,
    ageStatement: "2 Years",
    vintage: "",
    tags: ["Best Seller", "Aussie Icon", "Classic Dark Rum"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum", "best-sellers"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg UP Original Rum 1 Litre",
    brand: "Bundaberg Rum",
    price: 64.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "37.0%",
    size: "1L",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Dark Rum",
    style: "Australian Dark Rum; Cane Molasses",
    flavourProfile: ["Caramel", "Molasses", "Toasted Oak", "Treacle"],
    desc: "The 1 Litre value format of Australia's legendary Bundaberg UP Rum. Crafted from sweet cane molasses and matured in vat timber, delivering distinct toffee and oak warmth.",
    shortDesc: "1 Litre format of the legendary Australian Queensland dark rum.",
    badge: "1L Value",
    featured: false,
    ageStatement: "2 Years",
    vintage: "",
    tags: ["Value Size", "Aussie Icon"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg Red Rum Extra Smooth 700ml",
    brand: "Bundaberg Rum",
    price: 49.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "37.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Dark Rum",
    style: "Smooth Red Gum Vat Filtered Dark Rum",
    flavourProfile: ["Vanilla", "Red Gum Wood", "Caramel", "Honey"],
    desc: "Bundaberg Red is aged in selected oak barrels and gently filtered through native Australian Red Gum wood charcoal, yielding an exceptionally rounded, mellow rum with subtle honey and vanilla sweetness.",
    shortDesc: "Charcoal filtered through Australian red gum timber for unmatched smoothness.",
    badge: "Extra Smooth",
    featured: false,
    ageStatement: "2 Years",
    vintage: "",
    tags: ["Smooth Dark Rum", "Aussie Craft"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg Small Batch Reserve Rum 700ml",
    brand: "Bundaberg Rum",
    price: 84.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Premium Dark Rum",
    style: "Small Batch Craft Rum; Charred Oak & Cognac Cask",
    flavourProfile: ["Dark Chocolate", "Dried Fig", "Roasted Macadamia", "Vanilla Bean"],
    desc: "Crafted in bespoke small batches in Bundaberg's historic copper pot still and aged in heavily charred American oak barrels before finishing in select Cognac and port casks. Rich, multi-layered, and deeply satisfying.",
    shortDesc: "Award-winning Australian small batch rum aged in charred oak with notes of cocoa and fig.",
    badge: "Award Winner",
    featured: true,
    ageStatement: "Reserve",
    vintage: "",
    tags: ["Top Shelf", "Gift Idea", "Award Winner"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum", "gift-packs"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg Master Distillers Collection Solera Rum 700ml",
    brand: "Bundaberg Rum",
    price: 189.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Collector Solera Rum",
    style: "Solera System Aged Premium Australian Rum",
    flavourProfile: ["Treacle Toffee", "Cedarwood", "Black Cherry", "Dark Chocolate"],
    desc: "The pinnacle of Bundaberg craft. Matured through a fractional Spanish solera system incorporating historic reserve casks and finished in port casks. A complex masterpiece of dark fruits, cedar, and velvety caramel.",
    shortDesc: "Pinnacle solera-aged Australian rum with deep complexity, dark chocolate, and cedarwood.",
    badge: "Vault Allocation",
    featured: true,
    ageStatement: "Solera System",
    vintage: "",
    tags: ["Collector Pick", "Vault Allocation", "Luxury Gift"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg Overproof Rum 700ml",
    brand: "Bundaberg Rum",
    price: 74.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "57.7%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Overproof Rum",
    style: "High Proof Australian Dark Rum",
    flavourProfile: ["Molasses Warmth", "Charred Oak", "Caramelised Brown Sugar", "Cinnamon"],
    desc: "Bottled at the traditional maritime strength of 57.7% ABV (100 British Proof), Bundaberg Overproof delivers unfiltered molasses intensity, rich oak tannins, and powerful warmth for premium cocktails and sipping.",
    shortDesc: "Traditional 57.7% overproof Australian rum offering bold cane molasses and intense warmth.",
    badge: "57.7% Overproof",
    featured: false,
    ageStatement: "Overproof",
    vintage: "",
    tags: ["High Proof", "Overproof", "Cocktail Essential"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Beenleigh Artisanal Distillers Double Cask 5 Year Old Rum 700ml",
    brand: "Beenleigh",
    price: 74.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Beenleigh, Queensland",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Dark Rum",
    style: "Double Cask Aged Pot Still Rum",
    flavourProfile: ["Spiced Apple", "Honeycomb", "Toasted Oak", "Vanilla Cream"],
    desc: "From Australia’s oldest registered distillery (est. 1884) on the banks of the Albert River in Queensland. Double-cask matured in ex-brandy vats and American oak bourbon barrels for 5 full years.",
    shortDesc: "Aged 5 years in ex-brandy vats and bourbon oak by Australia's oldest distillery.",
    badge: "5YO Double Cask",
    featured: true,
    ageStatement: "5 Years",
    vintage: "",
    tags: ["Heritage Distiller", "Craft Pick", "Aussie Heritage"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Beenleigh 10 Year Old Single Barrel Rum 700ml",
    brand: "Beenleigh",
    price: 119.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Beenleigh, Queensland",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Single Barrel Rum",
    style: "10-Year-Old Copper Pot Still Single Barrel",
    flavourProfile: ["Dark Plum", "Tobacco Leaf", "Toffee", "Charred Oak"],
    desc: "Matured for a full decade in Queensland's sub-tropical climate. Copper pot distilled and aged exclusively in select American bourbon barrels, yielding an extraordinarily smooth and complex sipping rum.",
    shortDesc: "Sub-tropical 10-year single barrel rum aged in American oak with deep toffee and tobacco notes.",
    badge: "10YO Single Barrel",
    featured: false,
    ageStatement: "10 Years",
    vintage: "",
    tags: ["10 Year Old", "Collector Rum", "Gift Idea"],
    collections: ["spirits", "rum", "dark-rum", "australian-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Brix Gold Australian Rum 700ml",
    brand: "Brix Distillers",
    price: 84.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Surry Hills, Sydney, NSW",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Gold Rum",
    style: "Urban Craft Australian Gold Rum; Local Wine Cask Aged",
    flavourProfile: ["Butterscotch", "Apricot", "Brioche", "Vanilla Oak"],
    desc: "Handcrafted in Surry Hills, Sydney from 100% Australian sugarcane molasses. Distilled in a custom Australian copper pot still and aged in ex-red wine and ex-bourbon casks for balanced fruit and oak elegance.",
    shortDesc: "Sydney craft gold rum matured in Australian wine casks with butterscotch and dried stone fruit.",
    badge: "Sydney Craft",
    featured: true,
    ageStatement: "Craft Aged",
    vintage: "",
    tags: ["Sydney Distilled", "Craft Gold Rum", "Australian Spirits"],
    collections: ["spirits", "rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Brix Spiced Australian Rum 700ml",
    brand: "Brix Distillers",
    price: 79.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Surry Hills, Sydney, NSW",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Native Botanical Spiced Rum",
    flavourProfile: ["Native Lemon Myrtle", "Grapefruit Peel", "Cinnamon", "Vanilla"],
    desc: "Brix Spiced Rum combines Australian pot-distilled gold rum with native lemon myrtle, roasted grapefruit peel, cinnamon, and whole vanilla beans. Bright, zesty, and utterly distinct from conventional spiced rums.",
    shortDesc: "Infused with native Australian lemon myrtle, cinnamon, and fresh grapefruit peel.",
    badge: "Native Spiced",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Native Botanicals", "Spiced Rum", "Sydney Craft"],
    collections: ["spirits", "rum", "spiced-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Brix White Australian Rum 700ml",
    brand: "Brix Distillers",
    price: 74.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Surry Hills, Sydney, NSW",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "White Rum",
    style: "Unaged Australian Pure Pot Still White Rum",
    flavourProfile: ["Fresh Sugar Cane", "Lime Zest", "Green Apple", "White Pepper"],
    desc: "An unaged pure pot still white rum from Sydney. Crafted from premium Australian molasses, it bursts with aromas of grassy fresh cane, lime zest, and subtle pepper spice. The definitive base for Mojitos and Daiquiris.",
    shortDesc: "Vibrant pure pot still white rum with fresh sugarcane, lime zest, and bright fruit notes.",
    badge: "Pot Still White",
    featured: false,
    ageStatement: "Unaged",
    vintage: "",
    tags: ["White Rum", "Daiquiri Essential", "Sydney Craft"],
    collections: ["spirits", "rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Husk Distillers Pure Cane Agricole Cultivated Rum 700ml",
    brand: "Husk Distillers",
    price: 79.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Tumbulgum, Tweed Valley, NSW",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Rhum Agricole",
    style: "Australian Cultivated Pure Cane Juice Rum",
    flavourProfile: ["Fresh Crushed Cane", "Grass", "Papaya", "Citrus Blossom"],
    desc: "Distilled from 100% freshly crushed virgin sugarcane juice harvested on the Husk farm in the Tweed Valley caldera. Pure, unadulterated Australian Agricole-style rum with vibrant terroir and herbal freshness.",
    shortDesc: "Paddock-to-bottle pure cane juice rum harvested in the volcanic Tweed Valley.",
    badge: "Pure Cane Agricole",
    featured: true,
    ageStatement: "Pure Cane",
    vintage: "",
    tags: ["Rhum Agricole", "Farm Distillery", "Native Terroir"],
    collections: ["spirits", "rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Husk Distillers Spiced Bam Bam Rum 700ml",
    brand: "Husk Distillers",
    price: 84.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Australia",
    region: "Tumbulgum, Tweed Valley, NSW",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Aged Pure Cane Spiced Rum with Native Roasted Wattleseed",
    flavourProfile: ["Roasted Wattleseed", "Orange Peel", "Ginger", "Cinnamon"],
    desc: "Bam Bam is a farm-distilled pure cane rum aged 3 to 4 years in charred oak barrels and infused with native roasted wattleseed, ginger, whole cinnamon quills, and sun-dried orange peel.",
    shortDesc: "Barrel-aged Australian cane rum infused with native roasted wattleseed and ginger.",
    badge: "Wattleseed Spiced",
    featured: false,
    ageStatement: "3-4 Years",
    vintage: "",
    tags: ["Native Wattleseed", "Farm Spiced", "Premium Pick"],
    collections: ["spirits", "rum", "spiced-rum", "australian-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },

  // --- ICONIC SPICED RUMS ---
  {
    name: "The Kraken Black Spiced Rum 700ml",
    brand: "The Kraken",
    price: 54.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Trinidad & Tobago",
    region: "Caribbean",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Black Spiced Caribbean Rum",
    flavourProfile: ["Vanilla Bean", "Cinnamon", "Clove", "Ginger", "Dark Molasses"],
    desc: "The Kraken is an imported Caribbean black spiced rum enriched with exotic spices including cinnamon, ginger, and clove. Named after the mythical sea beast, it pours pitch black with rich, velvety spice.",
    shortDesc: "Legendary black spiced Caribbean rum infused with 11 secret warming spices.",
    badge: "Best Seller",
    featured: true,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Spiced Rum", "Best Seller", "Cocktail Favourite"],
    collections: ["spirits", "rum", "spiced-rum", "best-sellers"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "The Kraken Black Spiced Rum 1 Litre",
    brand: "The Kraken",
    price: 74.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Trinidad & Tobago",
    region: "Caribbean",
    abv: "40.0%",
    size: "1L",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Black Spiced Caribbean Rum",
    flavourProfile: ["Vanilla", "Espresso", "Clove", "Dark Chocolate"],
    desc: "The massive 1 Litre handle of The Kraken Black Spiced Rum. Packed with deep roasted caramel, rich vanilla, and warming aromatic spices.",
    shortDesc: "1 Litre bottle of the world-famous black spiced Caribbean rum.",
    badge: "1L Bottle",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Value 1L", "Spiced Rum"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "The Kraken Roast Coffee Black Spiced Rum 700ml",
    brand: "The Kraken",
    price: 57.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Trinidad & Tobago",
    region: "Caribbean",
    abv: "33.3%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum / Coffee Infusion",
    style: "Arabica Roast Coffee Spiced Rum",
    flavourProfile: ["Dark Roast Arabica Coffee", "Cinnamon", "Vanilla", "Brown Sugar"],
    desc: "A bold fusion of Caribbean black spiced rum and dark roasted Arabica coffee beans. Delivers rich espresso aromas alongside the Kraken signature vanilla and spice backbone.",
    shortDesc: "Black spiced rum infused with rich dark roast Arabica coffee beans.",
    badge: "Coffee Infusion",
    featured: false,
    ageStatement: "Infusion",
    vintage: "",
    tags: ["Coffee Rum", "Espresso Martini Pick"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Sailor Jerry Spiced Rum 700ml",
    brand: "Sailor Jerry",
    price: 52.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Virgin Islands",
    region: "Caribbean",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Old School Navy Spiced Rum",
    flavourProfile: ["Vanilla", "Nutmeg", "Cinnamon", "Toffee"],
    desc: "Crafted in the authentic tradition of sailor tattoo master Norman 'Sailor Jerry' Collins. Infused with natural vanilla, cinnamon, and nutmeg for a smooth, high-strength spiced rum that mixes perfectly with dry ginger and cola.",
    shortDesc: "Bold 40% navy-strength spiced rum with rich natural vanilla, cinnamon, and nutmeg.",
    badge: "Navy Spiced",
    featured: true,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Spiced Rum", "Cocktail Staple"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Sailor Jerry Spiced Rum 1 Litre",
    brand: "Sailor Jerry",
    price: 72.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Virgin Islands",
    region: "Caribbean",
    abv: "40.0%",
    size: "1L",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Old School Navy Spiced Rum",
    flavourProfile: ["Vanilla", "Nutmeg", "Cinnamon", "Toffee"],
    desc: "Generous 1 Litre bottle of Sailor Jerry Spiced Rum, bringing bold Caribbean character, warm spices, and smooth toffee notes.",
    shortDesc: "1 Litre format of Sailor Jerry Caribbean spiced rum.",
    badge: "1L Value",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["1L Bottle", "Spiced Rum"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Captain Morgan Original Spiced Gold Rum 700ml",
    brand: "Captain Morgan",
    price: 44.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Caribbean",
    abv: "35.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Gold Rum",
    style: "Caribbean Spiced Spirit",
    flavourProfile: ["Vanilla", "Brown Sugar", "Dried Fruit", "Warming Spice"],
    desc: "Captain Morgan Original Spiced Gold blends Caribbean rums with natural vanilla and aromatic spices, aged in charred white oak barrels for a signature smooth, sweet finish.",
    shortDesc: "World-famous Caribbean spiced gold rum with smooth vanilla and warming spices.",
    badge: "Party Staple",
    featured: true,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Party Essential", "Best Seller", "Spiced Rum"],
    collections: ["spirits", "rum", "spiced-rum", "party-drinks"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Captain Morgan Original Spiced Gold Rum 1 Litre",
    brand: "Captain Morgan",
    price: 62.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Caribbean",
    abv: "35.0%",
    size: "1L",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Gold Rum",
    style: "Caribbean Spiced Spirit",
    flavourProfile: ["Vanilla", "Brown Sugar", "Spiced Oak"],
    desc: "Value 1 Litre bottle of Captain Morgan Original Spiced Gold, ideal for parties, group gatherings, and continuous cocktail making.",
    shortDesc: "1 Litre bottle of Captain Morgan Original Spiced Gold.",
    badge: "1L Value",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["1L Value", "Spiced Rum"],
    collections: ["spirits", "rum", "spiced-rum", "party-drinks"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Captain Morgan Black Spiced Rum 700ml",
    brand: "Captain Morgan",
    price: 54.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Caribbean",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Black Spiced Rum",
    style: "Double Charred Barrel Aged Black Spiced Rum",
    flavourProfile: ["Clove", "Cassia Bark", "Caramelised Molasses", "Vanilla"],
    desc: "Crafted with black Caribbean rum and matured in double-charred black oak barrels for an intense, full-bodied spice profile and deep mahogany colour.",
    shortDesc: "Aged in double-charred oak barrels with cassia bark and dark molasses notes.",
    badge: "Black Spiced",
    featured: false,
    ageStatement: "Black Spiced",
    vintage: "",
    tags: ["Black Spiced", "Dark Rum"],
    collections: ["spirits", "rum", "spiced-rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Dead Man's Fingers Spiced Rum 700ml",
    brand: "Dead Man's Fingers",
    price: 49.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "United Kingdom",
    region: "Cornwall / Caribbean Blend",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Cornish Crafted Caribbean Blend Spiced Rum",
    flavourProfile: ["Pedro Ximenez Ice Cream", "Vanilla", "Nutmeg", "Orange Peel"],
    desc: "Created at the famous Rum & Crab Shack in St. Ives, Cornwall. Blends Trinidad and Guyanese rums with spices that evoke Pedro Ximénez ice cream, saffron cake, and fresh orange zest.",
    shortDesc: "Cornish craft spiced rum with notes of PX ice cream, nutmeg, and candied orange.",
    badge: "Cult Pick",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Cult Rum", "Spiced Rum"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },

  // --- PREMIUM AGED & DARK RUMS (CENTRAL & SOUTH AMERICA / CARIBBEAN) ---
  {
    name: "Diplomático Reserva Exclusiva Rum 700ml",
    brand: "Diplomático",
    price: 99.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Venezuela",
    region: "La Miel, Lara State",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Super Premium Dark Rum",
    style: "Copper Pot Still Aged Dark Rum (Aged up to 12 Years)",
    flavourProfile: ["Maple Syrup", "Orange Peel", "Brown Sugar", "Dark Toffee", "Cocoa"],
    desc: "Diplomático Reserva Exclusiva is a truly exquisite Venezuelan sipping rum. Composed of 80% heavy pot still rums aged for up to 12 years in small oak casks. Remarkable elegance, rich maple syrup sweetness, and orange peel complexity.",
    shortDesc: "Super-premium Venezuelan sipping rum aged up to 12 years with maple, toffee, and cocoa.",
    badge: "Collector Icon",
    featured: true,
    ageStatement: "Up to 12 Years",
    vintage: "",
    tags: ["Super Premium", "Gift Idea", "Best Seller"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100", "best-sellers"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Diplomático Selección de Familia Rum 700ml",
    brand: "Diplomático",
    price: 129.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Venezuela",
    region: "La Miel, Lara State",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Luxury Dark Rum",
    style: "Family Reserve Aged Rum; Ex-Bourbon & Sherry Cask",
    flavourProfile: ["Red Fruits", "Dark Plum", "Charred Oak", "Caramel Toffee"],
    desc: "Created by Diplomático's Maestros Roneros alongside the Ballesteros family. Aged up to 12 years primarily in American white oak bourbon casks before finishing in ex-Sherry casks for deeper dryness and plum complexity.",
    shortDesc: "Master blender reserve finished in Spanish sherry casks with plum, oak, and dark toffee.",
    badge: "Prestige Reserve",
    featured: false,
    ageStatement: "Up to 12 Years",
    vintage: "",
    tags: ["Prestige Reserve", "Sherry Cask", "Luxury Rum"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Ron Zacapa Centenario 23 Solera Gran Reserva Rum 700ml",
    brand: "Ron Zacapa",
    price: 124.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Guatemala",
    region: "Quetzaltenango Highlands (2,300m)",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Highland Solera Rum",
    style: "Sistema Solera 6-23 Years; Aged Above the Clouds",
    flavourProfile: ["Honeycomb", "Sweet Sherry", "Roasted Hazelnut", "Dark Chocolate", "Vanilla"],
    desc: "Crafted in the Guatemalan highlands at 2,300 metres above sea level using virgin sugar cane honey. Aged in a Sistema Solera incorporating ex-whiskey, delicate sherry, and Pedro Ximénez wine barrels.",
    shortDesc: "Aged above the clouds in Guatemala in Pedro Ximenez and sherry casks (6–23 years).",
    badge: "Solera 23",
    featured: true,
    ageStatement: "Solera 6-23",
    vintage: "",
    tags: ["Highland Solera", "Luxury Gift", "Top Shelf"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Ron Zacapa XO Gran Reserva Especial Rum 700ml",
    brand: "Ron Zacapa",
    price: 249.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Guatemala",
    region: "Quetzaltenango Highlands (2,300m)",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Ultra Luxury Solera Rum",
    style: "Solera 6-25 Years Finished in French Cognac Casks",
    flavourProfile: ["Black Cherry", "Dark Chocolate", "Toasted Almond", "Cognac Oak Spice"],
    desc: "A blend of reserve rums aged between 6 and 25 years, finished in French oak barrels previously used to mature fine Cognac. Presented in a breathtaking crystal decanter, offering peerless silkiness and dried fruit nuance.",
    shortDesc: "Ultra-luxury solera rum finished in French Cognac casks with black cherry and cocoa.",
    badge: "Vault Prestige",
    featured: true,
    ageStatement: "Solera 6-25",
    vintage: "",
    tags: ["Cognac Cask", "Decanter", "Vault Prestige"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts", "corporate-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Mount Gay XO Triple Cask Blend Rum 700ml",
    brand: "Mount Gay",
    price: 99.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados",
    region: "St. Lucy, Barbados",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Barbados Rum",
    style: "Triple Cask Blend (American Whiskey, Bourbon & Cognac Cask)",
    flavourProfile: ["Salted Caramel", "Baked Fig", "Dark Chocolate", "Clove Oak"],
    desc: "From Mount Gay in Barbados, the world's oldest commercial rum distillery (est. 1703). Triple Cask Blend combines pot and column still rums aged 5 to 17 years in American whiskey, bourbon, and Cognac casks.",
    shortDesc: "Triple cask Barbados rum aged 5–17 years in whiskey, bourbon, and Cognac barrels.",
    badge: "World's Oldest Distillery",
    featured: true,
    ageStatement: "5-17 Years Blend",
    vintage: "",
    tags: ["Barbados Rum", "Triple Cask", "Top Shelf"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Mount Gay Eclipse Heritage Rum 700ml",
    brand: "Mount Gay",
    price: 49.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados",
    region: "St. Lucy, Barbados",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Golden Rum",
    style: "Classic Bajan Gold Rum",
    flavourProfile: ["Apricot", "Banana", "Vanilla", "Toasted Oak"],
    desc: "The benchmark of Bajan rum. Distilled from column and copper pot stills and aged in toasted ex-American whiskey casks. Floral, fruity, with crisp vanilla and toasted wood accents.",
    shortDesc: "The golden standard of Barbados rum with bright fruit, vanilla, and gentle oak notes.",
    badge: "Bajan Classic",
    featured: false,
    ageStatement: "Eclipse Heritage",
    vintage: "",
    tags: ["Barbados Gold", "Classic Sipper"],
    collections: ["spirits", "rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Appleton Estate 12 Year Old Rare Casks Jamaica Rum 700ml",
    brand: "Appleton Estate",
    price: 89.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Nassau Valley",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Jamaica Rum",
    style: "Pot & Column Still Minimum 12 Year Aged Rum",
    flavourProfile: ["Orange Peel", "Dark Hazelnut", "Molasses Funk", "Rich Vanilla Oak"],
    desc: "A true minimum age statement rum from Jamaica's lush Nassau Valley. Matured for at least 12 tropical years in the heart of Jamaica. Showcases rich Jamaican pot-still 'hogo' funk alongside deep toasted wood and orange zest.",
    shortDesc: "Minimum 12 tropical years aged in American oak with hazelnut, orange peel, and Jamaican pot still character.",
    badge: "12YO Minimum Age",
    featured: true,
    ageStatement: "12 Years Minimum",
    vintage: "",
    tags: ["Jamaica Rum", "12 Year Old", "Award Winner"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Appleton Estate 21 Year Old Nassau Valley Casks Rum 700ml",
    brand: "Appleton Estate",
    price: 239.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Nassau Valley",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Luxury Aged Jamaica Rum",
    style: "Minimum 21 Year Old Tropical Oak Cask Aging",
    flavourProfile: ["Floral Orange Blossom", "Nutmeg", "Rich Roasted Coffee", "Dark Cocoa", "Smoked Oak"],
    desc: "A magnificent sipping rum, aged for a minimum of 21 tropical years in hand-selected Number One Select American oak barrels. Incredibly rare, silky, and complex with deep warm spices and molasses elegance.",
    shortDesc: "Rare 21-year minimum aged Jamaican rum with orange blossom, roasted coffee, and smoky oak.",
    badge: "21YO Vault",
    featured: true,
    ageStatement: "21 Years Minimum",
    vintage: "",
    tags: ["21 Year Old", "Vault Prestige", "Luxury Collector"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts", "corporate-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Appleton Estate Signature Jamaica Rum 700ml",
    brand: "Appleton Estate",
    price: 49.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Jamaica",
    region: "Nassau Valley",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Jamaica Rum",
    style: "Pot & Column Blend Jamaica Rum",
    flavourProfile: ["Dried Apricot", "Molasses", "Peach", "Warm Toast"],
    desc: "A delicious blend of pot and column rums, aged in Number One Select American oak barrels with an average age of 4 years. Fresh, fruit-forward, and indispensable for Mai Tais and Rum Punches.",
    shortDesc: "Versatile Jamaican rum blend with dried apricot, warm toast, and citrus zest.",
    badge: "Cocktail Gold",
    featured: false,
    ageStatement: "Signature",
    vintage: "",
    tags: ["Mai Tai Staple", "Jamaican Rum"],
    collections: ["spirits", "rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Planteray (Plantation) XO 20th Anniversary Rum 700ml",
    brand: "Planteray (Plantation)",
    price: 129.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados",
    region: "Caribbean / Cognac, France",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Luxury Double Aged Rum",
    style: "Tropical Bourbon Cask & French Ferrand Cognac Cask Aged",
    flavourProfile: ["Coconut Cream", "Candied Orange", "Vanilla Pod", "Milk Chocolate", "Toasted Oak"],
    desc: "First aged for many years in bourbon casks in Barbados, then shipped across the Atlantic to the Ferrand estate in Cognac, France, for further maturation in small French oak casks. Velvety, aromatic, and decadent.",
    shortDesc: "Double-aged in Barbados bourbon barrels and French Cognac casks with coconut and milk chocolate.",
    badge: "20th Anniversary",
    featured: true,
    ageStatement: "XO 20th Anniversary",
    vintage: "",
    tags: ["Double Aged", "Cognac Cask", "Luxury Gift"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Planteray (Plantation) Stiggins' Fancy Pineapple Rum 700ml",
    brand: "Planteray (Plantation)",
    price: 84.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados / Trinidad",
    region: "Caribbean / Cognac, France",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Infused Rum",
    style: "Queen Victoria Pineapple Barks & Fruit Infused Rum",
    flavourProfile: ["Roasted Pineapple", "Citrus Peel", "Smoked Wood", "Clove Spice"],
    desc: "A tribute to Reverend Stiggins in Charles Dickens' Pickwick Papers. Victorian Queen Victoria pineapples are infused into Plantation 3 Stars White Rum and Plantation Original Dark Rum before double distillation in copper pot stills.",
    shortDesc: "Artisanal infusion of Queen Victoria pineapple bark and fruit in premium Caribbean rum.",
    badge: "Pineapple Infusion",
    featured: false,
    ageStatement: "Artisanal",
    vintage: "",
    tags: ["Pineapple Rum", "Tiki Essential", "Award Winner"],
    collections: ["spirits", "rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Planteray (Plantation) Original Dark Rum 700ml",
    brand: "Planteray (Plantation)",
    price: 58.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados & Jamaica",
    region: "Caribbean / Cognac, France",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Dark Rum",
    style: "Barbados & Jamaica Double Aged Dark Rum",
    flavourProfile: ["Plum", "Banana", "Spiced Toffee", "Smoked Molasses"],
    desc: "Rich blend of pot still Jamaican rum and column still Barbados rum, matured in the tropics before finishing in French oak casks in southwestern France. The gold standard for dark rum cocktails.",
    shortDesc: "Rich double-aged Caribbean blend finished in French oak casks.",
    badge: "Bartender Choice",
    featured: false,
    ageStatement: "Original Dark",
    vintage: "",
    tags: ["Bartender Staple", "Dark Rum"],
    collections: ["spirits", "rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Planteray (Plantation) O.F.T.D. Overproof Artisanal Rum 700ml",
    brand: "Planteray (Plantation)",
    price: 94.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados, Jamaica & Guyana",
    region: "Caribbean Blend",
    abv: "69.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Overproof Rum",
    style: "69% ABV Old Fashioned Traditional Dark Rum",
    flavourProfile: ["Coffee Beans", "Cacao", "Molasses", "Prune", "Wood Smoke"],
    desc: "Created by Alexandre Gabriel alongside six world-renowned rum luminaries. Bottled at a ferocious 69% ABV, blending rums from Barbados, Guyana, and Jamaica. Essential for flaming garnishes, Zombie cocktails, and deep Tiki punches.",
    shortDesc: "Colossal 69% ABV overproof rum blend from Barbados, Jamaica, and Guyana.",
    badge: "69% Overproof",
    featured: false,
    ageStatement: "Overproof",
    vintage: "",
    tags: ["Overproof", "Tiki Legend", "High Proof"],
    collections: ["spirits", "rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Flor de Caña 12 Year Old Centenario Rum 700ml",
    brand: "Flor de Caña",
    price: 84.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Nicaragua",
    region: "Chichigalpa, San Cristóbal Volcano",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Centenario Rum",
    style: "Naturally Aged Carbon Neutral Volcanic Rum",
    flavourProfile: ["Red Apple", "Buttered Toffee", "Toasted Hazelnut", "Vanilla"],
    desc: "Naturally aged for 12 years in small bourbon barrels at the base of the active San Cristóbal volcano in Nicaragua. 100% sustainably produced, Carbon Neutral, and Fair Trade certified with zero added sugar.",
    shortDesc: "Naturally aged 12 years at the base of an active volcano; zero added sugar, Fair Trade certified.",
    badge: "Carbon Neutral",
    featured: true,
    ageStatement: "12 Years",
    vintage: "",
    tags: ["Sustainable", "Zero Sugar", "12 Year Old"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Flor de Caña 18 Year Old Centenario Rum 700ml",
    brand: "Flor de Caña",
    price: 139.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Nicaragua",
    region: "Chichigalpa, San Cristóbal Volcano",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Luxury Aged Rum",
    style: "18-Year Naturally Aged Single Estate Rum",
    flavourProfile: ["Dark Cocoa", "Roasted Almonds", "Oak Spice", "Dried Fig"],
    desc: "An extraordinary 18-year naturally aged rum from the Flor de Caña estate. Matured without artificial ingredients or accelerants in charred American oak casks for nearly two decades.",
    shortDesc: "Estate-grown volcanic rum aged naturally for 18 years with rich cocoa and spiced oak.",
    badge: "18YO Prestige",
    featured: false,
    ageStatement: "18 Years",
    vintage: "",
    tags: ["18 Year Old", "Prestige Rum", "Whisky Cask Alternative"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "El Dorado 12 Year Old Special Reserve Rum 700ml",
    brand: "El Dorado",
    price: 89.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Guyana",
    region: "Demerara River",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Demerara Aged Rum",
    style: "Historic Wooden Pot Still Aged Demerara Rum",
    flavourProfile: ["Tropical Fruits", "Nutmeg", "Smoky Molasses", "Dark Honey", "Toffee"],
    desc: "Distilled along the banks of Guyana's Demerara River using the world's last operational historic wooden Enmore and Port Mourant pot stills. Matured a minimum of 12 years in oak barrels.",
    shortDesc: "Historic wooden pot-still Demerara rum aged 12 years with deep honey and toffee.",
    badge: "Demerara 12YO",
    featured: true,
    ageStatement: "12 Years Minimum",
    vintage: "",
    tags: ["Demerara Rum", "Wooden Pot Still", "12 Year Old"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "El Dorado 15 Year Old Special Reserve Rum 700ml",
    brand: "El Dorado",
    price: 129.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Guyana",
    region: "Demerara River",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Demerara Aged Rum",
    style: "Minimum 15 Years Old Wooden Coffey & Pot Still Blend",
    flavourProfile: ["Dark Chocolate", "Candied Orange Peel", "Black Pepper", "Roasted Walnut", "Molasses"],
    desc: "Renowned by critics as one of the finest aged rums in the world. A minimum 15-year blend combining spirits from the historic wooden Coffey still and double wooden pot stills of Guyana.",
    shortDesc: "Critically acclaimed 15-year Demerara rum with rich dark chocolate, roasted walnut, and orange peel.",
    badge: "Demerara 15YO",
    featured: false,
    ageStatement: "15 Years Minimum",
    vintage: "",
    tags: ["Demerara Prestige", "15 Year Old", "Collector Rum"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Goslings Black Seal Bermuda Black Rum 700ml",
    brand: "Goslings",
    price: 64.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Bermuda",
    region: "Hamilton, Bermuda",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Black Rum",
    style: "Original Bermuda Black Rum",
    flavourProfile: ["Stewed Plum", "Molasses", "Charred Oak", "Butterscotch"],
    desc: "The authentic foundation of Bermuda's national cocktail, the Dark 'n Stormy®. Aged in charred American oak barrels for an extraordinarily rich, unctuous molasses profile.",
    shortDesc: "The original Bermuda black rum; essential for an authentic Dark 'n Stormy®.",
    badge: "Dark 'n Stormy®",
    featured: true,
    ageStatement: "Black Seal",
    vintage: "",
    tags: ["Dark n Stormy", "Black Rum", "Cocktail Staple"],
    collections: ["spirits", "rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Angostura 1824 12 Year Old Rum 700ml",
    brand: "Angostura",
    price: 119.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Trinidad & Tobago",
    region: "Port of Spain",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Trinidad Rum",
    style: "Hand-Blended 12 Year Old Bourbon Cask Rum",
    flavourProfile: ["Sweet Molasses", "Vanilla", "Honey", "Dried Raisin", "Charred Oak"],
    desc: "Celebrates the founding year of the House of Angostura. Hand-blended from select reserve rums aged a minimum of 12 years in charred American oak bourbon barrels, filtered, and hand-bottled.",
    shortDesc: "Hand-blended 12-year reserve rum from Trinidad with honey, dried raisin, and sweet oak.",
    badge: "1824 Reserve",
    featured: false,
    ageStatement: "12 Years Minimum",
    vintage: "",
    tags: ["Trinidad Rum", "12 Year Old", "Gift Idea"],
    collections: ["spirits", "rum", "dark-rum", "gifts-under-100"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },

  // --- CLASSIC WHITE & MIXING RUMS ---
  {
    name: "Bacardi Carta Blanca Superior White Rum 700ml",
    brand: "Bacardi",
    price: 42.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Puerto Rico",
    region: "Cataño / Caribbean",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "White Rum",
    style: "Charcoal Filtered Light Dry Rum",
    flavourProfile: ["Almond", "Lime Zest", "Vanilla", "Clean Floral Notes"],
    desc: "Created in 1862 by Don Facundo Bacardí Massó in Santiago de Cuba. Aged in white oak barrels and charcoal-filtered through a proprietary blend of coconut shell and wood charcoals for supreme cocktail clarity.",
    shortDesc: "The world's benchmark light white rum; charcoal filtered for crisp Mojitos and Daiquiris.",
    badge: "Global Classic",
    featured: true,
    ageStatement: "Carta Blanca",
    vintage: "",
    tags: ["White Rum", "Mojito Staple", "Best Seller"],
    collections: ["spirits", "rum", "best-sellers", "summer-drinks"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bacardi Carta Blanca Superior White Rum 1 Litre",
    brand: "Bacardi",
    price: 58.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Puerto Rico",
    region: "Cataño / Caribbean",
    abv: "37.5%",
    size: "1L",
    containerType: "Bottle",
    packSize: "Single",
    productType: "White Rum",
    style: "Charcoal Filtered Light Dry Rum",
    flavourProfile: ["Almond", "Lime Zest", "Crisp Floral"],
    desc: "The value 1 Litre bar bottle of Bacardi Carta Blanca Superior White Rum. Clean, dry, and balanced.",
    shortDesc: "1 Litre format of the legendary Bacardi Carta Blanca white rum.",
    badge: "1L Bottle",
    featured: false,
    ageStatement: "Carta Blanca",
    vintage: "",
    tags: ["1L Value", "White Rum"],
    collections: ["spirits", "rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bacardi Reserva Ocho (8 Year Old) Rare Rum 700ml",
    brand: "Bacardi",
    price: 69.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Puerto Rico",
    region: "Cataño / Caribbean",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Aged Gold Rum",
    style: "8-Year Barrel Aged Family Reserve Rum",
    flavourProfile: ["Dried Apricot", "Nutmeg", "Butterscotch", "Toasted Oak"],
    desc: "Created in 1862 and kept as the private reserve of the Bacardí family for seven generations. Each batch is aged for a minimum of 8 years in small oak barrels under the Caribbean sun.",
    shortDesc: "Historic family reserve aged 8 full years in oak with apricot, nutmeg, and butterscotch.",
    badge: "8YO Reserve",
    featured: true,
    ageStatement: "8 Years Minimum",
    vintage: "",
    tags: ["8 Year Old", "Family Reserve", "Aged Gold"],
    collections: ["spirits", "rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bacardi Spiced Rum 700ml",
    brand: "Bacardi",
    price: 44.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Puerto Rico",
    region: "Cataño / Caribbean",
    abv: "35.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Spiced Rum",
    style: "Charred American Oak Aged Spiced Spirit",
    flavourProfile: ["Creamy Vanilla", "Cinnamon", "Nutmeg", "Charred Wood"],
    desc: "Aged in charred American white oak barrels and infused with natural spices. Delivers creamy vanilla, warming cinnamon, and a hint of smoke.",
    shortDesc: "Aged in charred American oak with notes of creamy vanilla and cinnamon.",
    badge: "Spiced Classic",
    featured: false,
    ageStatement: "Spiced",
    vintage: "",
    tags: ["Spiced Rum", "Mixer Friendly"],
    collections: ["spirits", "rum", "spiced-rum"],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Havana Club Añejo 3 Años White Rum 700ml",
    brand: "Havana Club",
    price: 46.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Cuba",
    region: "Santa Cruz del Norte",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Cuban White Rum",
    style: "Aged 3 Years in White Oak & Filtered",
    flavourProfile: ["Sugarcane", "Citrus Blossom", "Caramelized Banana", "Smoked Oak"],
    desc: "The undisputed Cuban master for authentic Mojitos and Daiquiris. 100% crafted and aged in Cuba for 3 full years in ex-bourbon barrels, filtered to pale straw gold.",
    shortDesc: "Authentic 3-year aged Cuban white rum; the quintessential base for authentic Mojitos.",
    badge: "Cuban 3YO",
    featured: false,
    ageStatement: "3 Years",
    vintage: "",
    tags: ["Cuban Rum", "Authentic Mojito", "3 Year Old"],
    collections: ["spirits", "rum"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Havana Club Añejo 7 Años Dark Rum 700ml",
    brand: "Havana Club",
    price: 59.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Cuba",
    region: "San José de las Lajas",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Cuban Dark Rum",
    style: "Continuous Aging System Cuban Dark Rum (7 Years)",
    flavourProfile: ["Cuban Tobacco", "Sweet Tropical Fruit", "Dark Molasses", "Vanilla Cedar"],
    desc: "The quintessential Cuban dark sipping rum. Created by the legendary Don José Navarro using continuous aging batches. Showcases authentic notes of Cuban cigar tobacco, sweet tropical fruits, and toasted oak.",
    shortDesc: "Continuous solera-aged Cuban dark rum with notes of tobacco leaf, cedar, and vanilla.",
    badge: "Cuban 7YO",
    featured: true,
    ageStatement: "7 Years",
    vintage: "",
    tags: ["Cuban Dark Rum", "7 Year Old", "Classic Sipper"],
    collections: ["spirits", "rum", "dark-rum"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Havana Club Selección de Maestros Rum 700ml",
    brand: "Havana Club",
    price: 109.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Cuba",
    region: "San José de las Lajas",
    abv: "45.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Prestige Cuban Rum",
    style: "Barrel Proof Triple Barrel Aged Cuban Rum",
    flavourProfile: ["Pecan Nut", "Roasted Cocoa", "Candied Citrus", "Tobacco Smoke", "Oak Tannins"],
    desc: "Selected collectively by the Guild of Cuban Rum Masters (Maestros del Ron Cubano). Finished in specially selected aromatic white oak barrels and bottled directly at 45% ABV for supreme richness.",
    shortDesc: "Prestige 45% ABV Cuban rum selected by the Guild of Masters and finished in aromatic oak.",
    badge: "Guild of Masters",
    featured: false,
    ageStatement: "Selección de Maestros",
    vintage: "",
    tags: ["Cuban Prestige", "Guild of Masters", "Whisky Cask Alternative"],
    collections: ["spirits", "rum", "dark-rum", "whisky-gifts"],
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Malibu Caribbean White Rum with Coconut Flavour 700ml",
    brand: "Malibu",
    price: 39.99,
    category: "spirits",
    primaryCategory: "spirits",
    primarySubcategory: "rum",
    country: "Barbados",
    region: "Caribbean",
    abv: "21.0%",
    size: "700ml",
    containerType: "Bottle",
    packSize: "Single",
    productType: "Coconut Rum Liqueur",
    style: "Caribbean Rum with Natural Coconut Extract",
    flavourProfile: ["Sweet Coconut", "Fresh Sugarcane", "Vanilla", "Tropical Pineapple Notes"],
    desc: "The world’s favourite coconut-flavoured Caribbean rum. Distilled at the West Indies Rum Distillery in Barbados and blended with natural coconut extract. The ultimate shortcut to Piña Coladas and summer spritzes.",
    shortDesc: "Original Caribbean white rum blended with natural coconut extract for easy tropical cocktails.",
    badge: "Summer Icon",
    featured: false,
    ageStatement: "Flavoured",
    vintage: "",
    tags: ["Coconut Rum", "Pina Colada Essential", "Summer Drinks"],
    collections: ["spirits", "rum", "summer-drinks", "party-drinks", "gifts-under-50"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },

  // --- RUM PREMIX & RTD CANS / SLABS ---
  {
    name: "Bundaberg UP Rum & Cola 375ml Cans 10-Pack",
    brand: "Bundaberg Rum",
    price: 48.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "4.6%",
    size: "375ml x 10",
    containerType: "Can",
    packSize: "10-Pack",
    productType: "Rum RTD",
    style: "Dark Rum & Cola Premix",
    flavourProfile: ["Molasses Dark Rum", "Crisp Cola", "Caramel Oak"],
    desc: "Australia's premier rum premix. Perfectly balanced Bundaberg UP Dark Rum mixed with sparkling classic cola in handy 375ml cans.",
    shortDesc: "10-pack of Australia's favourite Bundaberg UP Dark Rum mixed with crisp cola.",
    badge: "10-Pack Cans",
    featured: true,
    ageStatement: "RTD",
    vintage: "",
    tags: ["10-Pack", "Aussie Icon", "Rum Premix", "BBQ Essential"],
    collections: ["premix-rtds", "rum-premix", "bbq-drinks", "party-drinks"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg UP Rum & Cola 375ml Cans 24-Can Slab Case",
    brand: "Bundaberg Rum",
    price: 109.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "4.6%",
    size: "375ml x 24",
    containerType: "Can",
    packSize: "24-Can Case",
    productType: "Rum RTD Slab",
    style: "Dark Rum & Cola Premix Slab",
    flavourProfile: ["Molasses Dark Rum", "Crisp Cola", "Caramel Oak"],
    desc: "Full 24-can slab case of legendary Bundaberg UP Rum & Cola. Stock up for footy weekends, camping trips, and backyard BBQs with wholesale case value.",
    shortDesc: "Full 24-can carton of classic Bundaberg UP Rum & Cola.",
    badge: "24-Can Slab",
    featured: true,
    ageStatement: "RTD Slab",
    vintage: "",
    tags: ["24-Can Case", "Slab Value", "Rum Premix", "Party Drinks"],
    collections: ["premix-rtds", "rum-premix", "party-drinks", "bbq-drinks"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Bundaberg Red Rum & Cola 375ml Cans 10-Pack",
    brand: "Bundaberg Rum",
    price: 51.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Australia",
    region: "Bundaberg, Queensland",
    abv: "4.6%",
    size: "375ml x 10",
    containerType: "Can",
    packSize: "10-Pack",
    productType: "Rum RTD",
    style: "Red Gum Charcoal Filtered Rum & Cola",
    flavourProfile: ["Smooth Red Gum Charcoal", "Vanilla", "Cola", "Molasses"],
    desc: "Bundaberg Red Rum filtered through red gum wood charcoal, pre-mixed with crisp cola for an ultra-smooth, mellow drinking experience.",
    shortDesc: "Smooth red-gum charcoal filtered Bundy Red rum mixed with refreshing cola.",
    badge: "Bundy Red",
    featured: false,
    ageStatement: "RTD",
    vintage: "",
    tags: ["10-Pack", "Extra Smooth", "Rum Premix"],
    collections: ["premix-rtds", "rum-premix"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Captain Morgan Spiced & Cola 375ml Cans 10-Pack",
    brand: "Captain Morgan",
    price: 46.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Jamaica",
    region: "Caribbean Blend",
    abv: "4.5%",
    size: "375ml x 10",
    containerType: "Can",
    packSize: "10-Pack",
    productType: "Spiced Rum RTD",
    style: "Spiced Gold Rum & Cola Premix",
    flavourProfile: ["Spiced Vanilla", "Warming Cinnamon", "Sweet Cola"],
    desc: "Captain Morgan Original Spiced Gold blended with refreshing cola in convenient 375ml cans. Delicious sweet vanilla notes with gentle warming spice.",
    shortDesc: "10-pack of Captain Morgan Spiced Gold Rum blended with refreshing cola.",
    badge: "Spiced & Cola",
    featured: false,
    ageStatement: "RTD",
    vintage: "",
    tags: ["10-Pack", "Spiced RTD", "Party Staple"],
    collections: ["premix-rtds", "rum-premix", "party-drinks"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "The Kraken Black Spiced Rum & Dry Ginger Ale 330ml Can 4-Pack",
    brand: "The Kraken",
    price: 26.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Trinidad & Tobago",
    region: "Caribbean Blend",
    abv: "5.5%",
    size: "330ml x 4",
    containerType: "Can",
    packSize: "4-Pack",
    productType: "Craft Rum RTD",
    style: "Black Spiced Rum & Fiery Dry Ginger Ale",
    flavourProfile: ["Black Spice", "Ginger Heat", "Vanilla", "Lime"],
    desc: "The Kraken Black Spiced Rum paired with fiery dry ginger ale. Bottled at 5.5% ABV for a robust, spicy kick and invigorating fizz.",
    shortDesc: "Bold 5.5% black spiced rum mixed with fiery dry ginger ale in sleek cans.",
    badge: "5.5% Craft RTD",
    featured: false,
    ageStatement: "RTD",
    vintage: "",
    tags: ["4-Pack", "Ginger Ale", "Kraken RTD"],
    collections: ["premix-rtds", "rum-premix"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  },
  {
    name: "Brix Spiced Rum & Ginger Beer 330ml Can 4-Pack",
    brand: "Brix Distillers",
    price: 28.99,
    category: "premix-rtds",
    primaryCategory: "premix-rtds",
    primarySubcategory: "rum-premix",
    country: "Australia",
    region: "Surry Hills, Sydney, NSW",
    abv: "6.0%",
    size: "330ml x 4",
    containerType: "Can",
    packSize: "4-Pack",
    productType: "Australian Craft RTD",
    style: "Native Spiced Rum & Australian Ginger Beer",
    flavourProfile: ["Native Lemon Myrtle", "Fiery Ginger", "Vanilla", "Grapefruit Peel"],
    desc: "Sydney craft at its finest. Brix Spiced Rum infused with native lemon myrtle and roasted grapefruit, blended with fiery Australian ginger beer. Crisp, spicy, and refreshingly complex.",
    shortDesc: "Sydney craft spiced rum infused with lemon myrtle, blended with fiery ginger beer.",
    badge: "Craft Premix",
    featured: true,
    ageStatement: "RTD",
    vintage: "",
    tags: ["4-Pack", "Aussie Craft RTD", "Sydney Distilled"],
    collections: ["premix-rtds", "rum-premix"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"
  }
];
