import fs from 'fs';

// Exact 90 Rum Expressions
export const EXACT_RUMS = [
  // 1. Bundaberg Original UP Rum
  {
    name: "Bundaberg Original UP Rum",
    brand: "Bundaberg Rum",
    price: 49.99,
    rumStyle: "Dark",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "2 Years",
    abv: "37.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Handcrafted American White Oak Vats",
    flavourProfile: ["Caramel", "Molasses", "Toasted Oak", "Golden Syrup"],
    desc: "Bundaberg Underproof (UP) Rum is an Australian icon, distilled from 100% Queensland sugarcane molasses and aged for a minimum of two years in rich American white oak vats handcrafted in Bundaberg.",
    shortDesc: "Iconic Australian dark rum aged in American oak vats with rich notes of molasses and caramel.",
    badge: "Aussie Icon",
    featured: true,
    variants: [
      { size: "700ml", price: 49.99, isDefault: true },
      { size: "1L", price: 64.99, isDefault: false }
    ],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 2. Bundaberg Overproof Rum
  {
    name: "Bundaberg Overproof Rum",
    brand: "Bundaberg Rum",
    price: 64.99,
    rumStyle: "Overproof",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "2 Years",
    abv: "57.7%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured in American Oak Vats",
    flavourProfile: ["Intense Molasses", "Charred Oak", "Cinnamon", "Brown Sugar"],
    desc: "Bottled at the traditional 57.7% maritime strength, Bundaberg Overproof delivers unfiltered molasses intensity, rich oak tannins, and powerful warmth for premium mixing and classic cocktails.",
    shortDesc: "Traditional 57.7% overproof Australian rum offering bold cane molasses and intense warmth.",
    badge: "57.7% ABV",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 3. Bundaberg Small Batch Distillery Edition Rum
  {
    name: "Bundaberg Small Batch Distillery Edition Rum",
    brand: "Bundaberg Rum",
    price: 79.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "Reserve",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Heavily Charred American Oak & Cognac Cask Finish",
    flavourProfile: ["Dark Chocolate", "Dried Fig", "Roasted Macadamia", "Vanilla Bean"],
    desc: "Crafted in bespoke small batches in Bundaberg's historic copper pot still and aged in heavily charred American oak barrels before finishing in select Cognac and port casks.",
    shortDesc: "Award-winning Australian small batch rum aged in charred oak with notes of cocoa and fig.",
    badge: "Distillery Edition",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 4. Bundaberg Master Distillers’ Collection Rum
  {
    name: "Bundaberg Master Distillers’ Collection Rum",
    brand: "Bundaberg Rum",
    price: 99.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "Solera Blend",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Port & Sherry Cask Maturation",
    flavourProfile: ["Treacle Toffee", "Cedarwood", "Black Cherry", "Dark Chocolate"],
    desc: "The pinnacle of Bundaberg craft. Matured through a fractional Spanish solera system incorporating historic reserve casks and finished in port and sherry casks.",
    shortDesc: "Pinnacle solera-aged Australian rum with deep complexity, dark chocolate, and cedarwood.",
    badge: "Master Distillers",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 5. Bundaberg Blenders Edition Rum
  {
    name: "Bundaberg Blenders Edition Rum",
    brand: "Bundaberg Rum",
    price: 89.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "Special Reserve",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Ex-Bourbon & Sweet Fortified Wine Barrels",
    flavourProfile: ["Butterscotch", "Raisin", "Toasted Oak", "Spice"],
    desc: "Blended by Bundaberg's master blending team from rare reserve casks. Delivers luxurious notes of butterscotch, sun-dried raisins, and velvety oak sweetness.",
    shortDesc: "Masterful blend of aged reserve rums with rich butterscotch, raisin, and toasted oak.",
    badge: "Blenders Edition",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 6. Beenleigh Double Cask Rum
  {
    name: "Beenleigh Double Cask Rum",
    brand: "Beenleigh",
    price: 69.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh",
    ageStatement: "5 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Ex-Brandy Vats & American Oak Bourbon Barrels",
    flavourProfile: ["Spiced Apple", "Honeycomb", "Toasted Oak", "Vanilla Cream"],
    desc: "From Australia’s oldest registered distillery (est. 1884). Double-cask matured in historic ex-brandy vats and charred American oak bourbon barrels for 5 full years.",
    shortDesc: "Aged 5 years in ex-brandy vats and bourbon oak by Australia's oldest distillery.",
    badge: "Double Cask",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 7. Beenleigh XO Rum
  {
    name: "Beenleigh XO Rum",
    brand: "Beenleigh",
    price: 79.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh",
    ageStatement: "XO Reserve",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Select Small Charred Oak Barrels",
    flavourProfile: ["Dark Honey", "Toffee", "Clove", "Mellow Wood"],
    desc: "A rich XO reserve rum aged gracefully in sub-tropical Queensland cellars. Packed with dark honey, buttery toffee, warm clove spice, and lingering oak.",
    shortDesc: "Extra Old reserve rum boasting deep golden amber hue, toffee, and warm spice.",
    badge: "XO Reserve",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 8. Beenleigh 10 Year Old Rum
  {
    name: "Beenleigh 10 Year Old Rum",
    brand: "Beenleigh",
    price: 109.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh",
    ageStatement: "10 Years",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "10-Year Single Barrel American Oak",
    flavourProfile: ["Dark Plum", "Tobacco Leaf", "Toffee", "Charred Oak"],
    desc: "Matured for a full decade in Queensland's sub-tropical climate. Copper pot distilled and aged exclusively in select American bourbon barrels.",
    shortDesc: "Sub-tropical 10-year single barrel rum aged in American oak with deep toffee and tobacco notes.",
    badge: "10YO Single Barrel",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 9. Beenleigh 12 Year Old Rum
  {
    name: "Beenleigh 12 Year Old Rum",
    brand: "Beenleigh",
    price: 129.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh",
    ageStatement: "12 Years",
    abv: "45.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "12-Year Small Batch Oak Maturation",
    flavourProfile: ["Dried Figs", "Dark Molasses", "Roasted Walnut", "Smoked Oak"],
    desc: "An extraordinary 12-year expression of Australian distilling history. Hand-selected barrels deliver intense wood depth, fig, and roasted walnut complexity.",
    shortDesc: "Rare 12-year-old Australian copper pot rum with rich dried fruit, walnut, and smoke.",
    badge: "12YO Rare Cask",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 10. Beenleigh Artisan Distillers Selection Rum
  {
    name: "Beenleigh Artisan Distillers Selection Rum",
    brand: "Beenleigh",
    price: 89.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh",
    ageStatement: "Distillers Selection",
    abv: "42.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Selected French Oak & Fortified Wine Casks",
    flavourProfile: ["Candied Citrus", "Vanilla Bean", "Golden Syrup", "Almond"],
    desc: "Specially curated by Beenleigh's head distiller to showcase the finest barrel blending from the Albert River cellars.",
    shortDesc: "Curated artisan release showcasing sweet candied citrus, vanilla, and fortified wine cask nuance.",
    badge: "Artisan Selection",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 11. Brix Australian Rum
  {
    name: "Brix Australian Rum",
    brand: "Brix Distillers",
    price: 69.99,
    rumStyle: "Gold",
    country: "Australia",
    state: "New South Wales",
    region: "Surry Hills, Sydney",
    ageStatement: "Craft Aged",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Australian Red Wine & Bourbon Barrels",
    flavourProfile: ["Butterscotch", "Apricot", "Brioche", "Vanilla Oak"],
    desc: "Handcrafted in Surry Hills, Sydney from 100% Australian sugarcane molasses. Distilled in a bespoke Australian copper pot still and aged in ex-red wine and bourbon casks.",
    shortDesc: "Sydney craft rum matured in Australian wine casks with butterscotch and dried stone fruit.",
    badge: "Sydney Craft",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 12. Brix Spiced Rum
  {
    name: "Brix Spiced Rum",
    brand: "Brix Distillers",
    price: 69.99,
    rumStyle: "Spiced",
    country: "Australia",
    state: "New South Wales",
    region: "Surry Hills, Sydney",
    ageStatement: "Spiced Infusion",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Pot Still Rum Infused with Native Botanicals",
    flavourProfile: ["Native Lemon Myrtle", "Grapefruit Peel", "Cinnamon", "Vanilla"],
    desc: "Brix Spiced Rum combines Australian pot-distilled gold rum with native lemon myrtle, roasted grapefruit peel, cinnamon, and whole vanilla beans.",
    shortDesc: "Infused with native Australian lemon myrtle, cinnamon, and fresh grapefruit peel.",
    badge: "Native Spiced",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 13. Brix Gold Rum
  {
    name: "Brix Gold Rum",
    brand: "Brix Distillers",
    price: 79.99,
    rumStyle: "Gold",
    country: "Australia",
    state: "New South Wales",
    region: "Surry Hills, Sydney",
    ageStatement: "Select Cask",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Select Australian Stout & Shiraz Casks",
    flavourProfile: ["Roasted Coffee", "Dark Caramel", "Shiraz Berry", "Toasted Brioche"],
    desc: "Premium gold edition aged in a marriage of Australian craft stout and Barossa Shiraz barrels, offering rich malt complexity and dark fruit finish.",
    shortDesc: "Rich Australian gold rum matured in Shiraz and craft stout casks.",
    badge: "Gold Edition",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 14. Husk Bam Bam Spiced Rum
  {
    name: "Husk Bam Bam Spiced Rum",
    brand: "Husk Distillers",
    price: 69.99,
    rumStyle: "Spiced",
    country: "Australia",
    state: "New South Wales",
    region: "Tweed Valley",
    ageStatement: "3-4 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Charred Oak & Infused with Native Wattleseed",
    flavourProfile: ["Roasted Wattleseed", "Orange Peel", "Ginger", "Cinnamon"],
    desc: "Bam Bam is a farm-distilled pure cane rum aged 3 to 4 years in charred oak barrels and infused with native roasted wattleseed, ginger, and sun-dried orange peel.",
    shortDesc: "Barrel-aged Australian cane rum infused with native roasted wattleseed and ginger.",
    badge: "Wattleseed Spiced",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 15. Husk Pure Cane Rum
  {
    name: "Husk Pure Cane Rum",
    brand: "Husk Distillers",
    price: 74.99,
    rumStyle: "Cane Juice",
    country: "Australia",
    state: "New South Wales",
    region: "Tweed Valley",
    ageStatement: "Unaged Pure Cane",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Unaged Fresh Cane Distillation",
    flavourProfile: ["Fresh Crushed Cane", "Grassy Terroir", "Papaya", "Citrus Blossom"],
    desc: "Distilled from 100% freshly crushed virgin sugarcane juice harvested on the Husk farm in the Tweed Valley caldera. Pure, unadulterated Australian Agricole-style rum.",
    shortDesc: "Paddock-to-bottle pure cane juice rum harvested in the volcanic Tweed Valley.",
    badge: "Pure Cane",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 16. Husk Rare Blend Rum
  {
    name: "Husk Rare Blend Rum",
    brand: "Husk Distillers",
    price: 99.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "New South Wales",
    region: "Tweed Valley",
    ageStatement: "Single Cask Release",
    abv: "44.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Virgin French Oak & Bourbon Casks",
    flavourProfile: ["Honeysuckle", "Smoked Toffee", "Cedar", "Wild Berry"],
    desc: "A rare limited bottling blending select single barrels of aged paddock-to-bottle cultivated cane spirit matured in virgin French oak.",
    shortDesc: "Rare limited barrel release of cultivated pure cane rum aged in French oak.",
    badge: "Rare Blend",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 17. Husk Agricole Rum
  {
    name: "Husk Agricole Rum",
    brand: "Husk Distillers",
    price: 89.99,
    rumStyle: "Agricole",
    country: "Australia",
    state: "New South Wales",
    region: "Tweed Valley",
    ageStatement: "Aged Agricole",
    abv: "42.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Ex-Bourbon Barrels & Charred Australian Oak",
    flavourProfile: ["Herbal Cane", "Earthy Terroir", "Vanilla", "Lime Blossom"],
    desc: "Aged Australian Rhum Agricole made from first-press sugarcane juice, aged in climate-responsive volcanic cellars in Northern NSW.",
    shortDesc: "Authentic Australian Agricole aged in oak with grassy freshness and vanilla warmth.",
    badge: "Cultivated Agricole",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 18. Inner Circle Green Dot Rum
  {
    name: "Inner Circle Green Dot Rum",
    brand: "Inner Circle",
    price: 79.99,
    rumStyle: "Overproof",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh / Bundaberg Heritage",
    ageStatement: "Overproof 57.2%",
    abv: "57.2%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "100% Pot Still Aged in Vintage Oak",
    flavourProfile: ["Demerara Sugar", "Cinnamon Quill", "Dark Toffee", "Bold Oak Tannin"],
    desc: "The historic distillery boardroom rum of CSR sugar millers. The legendary Green Dot is bottled at 57.2% ABV (100 proof) delivering intense pot-still depth.",
    shortDesc: "Legendary 57.2% Australian pot still rum with deep Demerara molasses and spice.",
    badge: "57.2% Green Dot",
    featured: true,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 19. Inner Circle Black Cask Strength Rum
  {
    name: "Inner Circle Black Cask Strength Rum",
    brand: "Inner Circle",
    price: 119.99,
    rumStyle: "Cask Strength",
    country: "Australia",
    state: "Queensland",
    region: "Beenleigh / Bundaberg Heritage",
    ageStatement: "Cask Strength 75.9%",
    abv: "75.9%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Uncut Vintage Pot Still Oak",
    flavourProfile: ["Intense Molasses", "Black Liquorice", "Espresso", "Smoked Wood"],
    desc: "Australia’s most formidable rum. Bottled at an astronomical 75.9% ABV (133 proof) straight from the barrel. A collector benchmark for bold rum cocktails.",
    shortDesc: "Ferocious 75.9% cask strength pot still rum delivering unparalleled power.",
    badge: "75.9% Cask Strength",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 20. Illegal Tender Spiced Rum
  {
    name: "Illegal Tender Spiced Rum",
    brand: "Illegal Tender Rum Co",
    price: 79.99,
    rumStyle: "Spiced",
    country: "Australia",
    state: "Western Australia",
    region: "Dongara, Midwest WA",
    ageStatement: "Craft Spiced",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Infused with Native Australian Desert Botanicals",
    flavourProfile: ["Quandong", "Lemon Myrtle", "Native Pepperberry", "Caramel"],
    desc: "Crafted in Dongara, Western Australia, using pure rainwater and local WA sugarcane. Infused with quandong, native lemon myrtle, and pepperberry.",
    shortDesc: "Award-winning WA spiced rum infused with quandong and native pepperberry.",
    badge: "WA Craft",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 21. Illegal Tender 1802 Rum
  {
    name: "Illegal Tender 1802 Rum",
    brand: "Illegal Tender Rum Co",
    price: 89.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Western Australia",
    region: "Dongara, Midwest WA",
    ageStatement: "2-3 Years",
    abv: "42.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Ex-Swan Valley Shiraz & Bourbon Casks",
    flavourProfile: ["Berry Compote", "Vanilla", "Toasted Oak", "Brown Sugar"],
    desc: "Commemorates the French exploration of Western Australia in 1802. Aged in Swan Valley Shiraz casks for luscious red fruit and caramel warmth.",
    shortDesc: "Aged in WA Shiraz barrels for luscious red berry and toasted caramel complexity.",
    badge: "Shiraz Cask Aged",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 22. Illegal Tender Distiller’s Cut Rum
  {
    name: "Illegal Tender Distiller’s Cut Rum",
    brand: "Illegal Tender Rum Co",
    price: 109.99,
    rumStyle: "Cask Strength",
    country: "Australia",
    state: "Western Australia",
    region: "Dongara, Midwest WA",
    ageStatement: "Distillers Cut",
    abv: "53.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Single Cask Uncut WA Oak",
    flavourProfile: ["Toffee Crisp", "Dark Chocolate", "Fig", "Charred Cask"],
    desc: "Single cask release bottled at a robust 53.0% ABV, capturing the raw, unadulterated heart of Midwest WA pot distillation.",
    shortDesc: "High-proof 53% distiller cut single barrel rum from Dongara, Western Australia.",
    badge: "Distiller's Cut",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 23. JimmyRum Silver Rum
  {
    name: "JimmyRum Silver Rum",
    brand: "JimmyRum",
    price: 74.99,
    rumStyle: "White",
    country: "Australia",
    state: "Victoria",
    region: "Mornington Peninsula",
    ageStatement: "Unaged Pure Pot Still",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Custom Italian Copper Pot Still Distillation",
    flavourProfile: ["Fresh Melon", "Crushed Grass", "Citrus Zest", "Clean Cane"],
    desc: "From Victoria’s first dedicated craft rum distillery on the Mornington Peninsula. Distilled in 'Matilda', a custom copper pot still, offering crisp tropical fruit.",
    shortDesc: "Mornington Peninsula pure pot still white rum with melon, citrus, and clean cane.",
    badge: "Mornington Craft",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 24. JimmyRum Navy Strength Rum
  {
    name: "JimmyRum Navy Strength Rum",
    brand: "JimmyRum",
    price: 89.99,
    rumStyle: "Navy Strength",
    country: "Australia",
    state: "Victoria",
    region: "Mornington Peninsula",
    ageStatement: "Navy 57.2%",
    abv: "57.2%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Oaked in Small Bourbon Barrels",
    flavourProfile: ["Butterscotch", "Sea Salt", "Vanilla Pod", "Warming Spice"],
    desc: "Bottled at maritime 57.2% ABV. Rich, viscous, and brimming with butterscotch, vanilla pod, and maritime warmth.",
    shortDesc: "Maritime 57.2% navy strength Victorian rum with rich butterscotch and sea spray.",
    badge: "57.2% Navy",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 25. JimmyRum Oaked Rum
  {
    name: "JimmyRum Oaked Rum",
    brand: "JimmyRum",
    price: 89.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Victoria",
    region: "Mornington Peninsula",
    ageStatement: "Barrel Matured",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in American Oak Bourbon Barrels",
    flavourProfile: ["Caramelised Pear", "Vanilla Custard", "Nutmeg", "Toasted Oak"],
    desc: "Matured on the Mornington Peninsula in select American bourbon casks, blending Australian molasses richness with sweet toasted oak.",
    shortDesc: "Smooth Victorian oak-matured rum with caramelised pear and vanilla custard.",
    badge: "Oaked Edition",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 26. Hoochery Kimberley Rum
  {
    name: "Hoochery Kimberley Rum",
    brand: "The Hoochery",
    price: 74.99,
    rumStyle: "Dark",
    country: "Australia",
    state: "Western Australia",
    region: "Kununurra, East Kimberley",
    ageStatement: "Aged in Tropical Heat",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Charred Oak in Extreme Kimberley Tropical Heat",
    flavourProfile: ["Kimberley Sugarcane", "Rich Caramel", "Charred Timber", "Tropical Spice"],
    desc: "From WA’s oldest continuously operating legal distillery in Kununurra. Fermented with local Ord River cane and matured in blistering 40°C Kimberley heat.",
    shortDesc: "Kimberley pot-still rum matured in tropical heat for accelerated oak extraction.",
    badge: "Kimberley Distilled",
    featured: true,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 27. Hoochery Ord River Rum
  {
    name: "Hoochery Ord River Rum",
    brand: "The Hoochery",
    price: 84.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Western Australia",
    region: "Kununurra, East Kimberley",
    ageStatement: "Premium Reserve",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in American Oak Bourbon Barrels",
    flavourProfile: ["Golden Honey", "Toffee", "Earthy Spice", "Vanilla"],
    desc: "Distilled from local Ord River sugarcane syrup and rainwater, aged in hand-selected charred oak barrels for deep outback character.",
    shortDesc: "Distilled from pristine Ord River sugarcane syrup and aged in charred American oak.",
    badge: "Ord River",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 28. Hoochery Spike’s Reserve Rum
  {
    name: "Hoochery Spike’s Reserve Rum",
    brand: "The Hoochery",
    price: 99.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Western Australia",
    region: "Kununurra, East Kimberley",
    ageStatement: "Spike's Reserve 54%",
    abv: "54.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Selected Charred Oak Barrels",
    flavourProfile: ["Intense Dark Treacle", "Smoky Cask", "Dried Plum", "Black Pepper"],
    desc: "Named in memory of founder Spike Dessert. Bottled at 54% ABV, showcasing the boldest, darkest barrels in the Kununurra bond stores.",
    shortDesc: "Tribute 54% ABV high-proof reserve rum packed with dark treacle and smoke.",
    badge: "Founder's Reserve",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 29. Kalki Moon White Rum
  {
    name: "Kalki Moon White Rum",
    brand: "Kalki Moon",
    price: 69.99,
    rumStyle: "White",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "Unaged Pot Still",
    abv: "37.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Pure Pot Still Double Distillation",
    flavourProfile: ["Sweet Molasses", "Lime Zest", "Coconut Water", "Crisp Pepper"],
    desc: "Distilled in Bundaberg, Queensland, by master distiller Rick Prosser. Pure pot-still white rum made from local molasses for pristine Mojitos and Daiquiris.",
    shortDesc: "Bundaberg craft pot-still white rum with sweet molasses and crisp lime notes.",
    badge: "Bundaberg Craft",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 30. Kalki Moon Spiced Rum
  {
    name: "Kalki Moon Spiced Rum",
    brand: "Kalki Moon",
    price: 69.99,
    rumStyle: "Spiced",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "Botanical Spiced",
    abv: "37.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Infused with Vanilla, Cinnamon & Roasted Ginger",
    flavourProfile: ["Warm Vanilla", "Ginger Root", "Cinnamon", "Candied Orange"],
    desc: "Blends Bundaberg pot-distilled rum with natural vanilla bean, fiery ginger root, and sweet spices for the ultimate Queensland spiced spirit.",
    shortDesc: "Queensland artisan spiced rum infused with real ginger root and vanilla.",
    badge: "Spiced Gold",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 31. Kalki Moon Barrel Aged Rum
  {
    name: "Kalki Moon Barrel Aged Rum",
    brand: "Kalki Moon",
    price: 79.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Bundaberg",
    ageStatement: "2+ Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Ex-Bourbon & Port Casks",
    flavourProfile: ["Caramelised Fig", "Butterscotch", "Toasted Oak", "Gentle Spice"],
    desc: "Aged for over two years in American bourbon and French port barrels in Bundaberg, delivering balanced sweetness and rich wood complexity.",
    shortDesc: "Bundaberg barrel-aged craft rum matured in bourbon and port casks.",
    badge: "Barrel Aged",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 32. Nil Desperandum 10 Year Old Rum
  {
    name: "Nil Desperandum 10 Year Old Rum",
    brand: "Nil Desperandum",
    price: 129.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Sunshine Coast",
    ageStatement: "10 Years",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Certified Organic Molasses Aged in Bourbon & Sherry Casks",
    flavourProfile: ["Candied Pecan", "Dark Chocolate", "Dried Cherry", "Vanilla Bean"],
    desc: "Australia’s first certified organic rum distillery on the Sunshine Coast. Matured for a full decade in small casks for breathtaking silkiness.",
    shortDesc: "Sunshine Coast certified organic 10-year rum aged in bourbon and sherry oak.",
    badge: "Organic 10YO",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 33. Nil Desperandum 12 Year Old Rum
  {
    name: "Nil Desperandum 12 Year Old Rum",
    brand: "Nil Desperandum",
    price: 149.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "Queensland",
    region: "Sunshine Coast",
    ageStatement: "12 Years",
    abv: "45.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "12 Years in Ex-Bourbon & European Port Pipes",
    flavourProfile: ["Black Forest Cake", "Tobacco", "Leather", "Rich Molasses"],
    desc: "The crown jewel of organic Australian distilling. 12 long years of tropical maturation yield extraordinary depth, cocoa, and velvet warmth.",
    shortDesc: "Masterpiece 12-year certified organic rum aged in bourbon and port pipes.",
    badge: "Organic 12YO",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 34. Lord Byron Original Rum
  {
    name: "Lord Byron Original Rum",
    brand: "Lord Byron Distillery",
    price: 69.99,
    rumStyle: "Aged",
    country: "Australia",
    state: "New South Wales",
    region: "Byron Bay",
    ageStatement: "Small Batch Aged",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in American Oak Bourbon Barrels",
    flavourProfile: ["Honeyed Toffee", "Vanilla", "Tropical Fruit", "Subtle Oak"],
    desc: "Handcrafted in Byron Bay using 100% renewable energy and local molasses. Zero artificial colours or additives, carbon-positive distillery.",
    shortDesc: "Byron Bay carbon-positive craft rum aged in bourbon oak with pure honeyed toffee notes.",
    badge: "Byron Bay Craft",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 35. Lord Byron Cane Spirit Rum
  {
    name: "Lord Byron Cane Spirit Rum",
    brand: "Lord Byron Distillery",
    price: 74.99,
    rumStyle: "Cane Juice",
    country: "Australia",
    state: "New South Wales",
    region: "Byron Bay",
    ageStatement: "Pure Cane Spirit",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Distilled from Fresh Local Sugarcane Juice",
    flavourProfile: ["Green Banana", "Grassy Cane", "Citrus Blossom", "White Pepper"],
    desc: "Distilled from freshly pressed Northern Rivers sugarcane juice. Pure, aromatic, and vibrant, ideal for artisanal Ti' Punch and Daiquiris.",
    shortDesc: "Vibrant Byron Bay pure cane spirit distilled from fresh Northern Rivers cane juice.",
    badge: "Pure Cane",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 36. Archie Rose White Cane Rum
  {
    name: "Archie Rose White Cane Rum",
    brand: "Archie Rose",
    price: 69.99,
    rumStyle: "Cane Juice",
    country: "Australia",
    state: "New South Wales",
    region: "Sydney",
    ageStatement: "Unaged Cane",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Sydney Copper Pot Distilled Unaged Cane",
    flavourProfile: ["Marshmallow", "Fresh Cane", "Kaffir Lime", "Green Apple"],
    desc: "Distilled from cold-pressed NSW sugarcane molasses in Sydney's custom copper pot stills. Unaged and bursting with floral cane and marshmallow.",
    shortDesc: "Sydney copper pot white cane spirit with notes of marshmallow and fresh kaffir lime.",
    badge: "Sydney Distilled",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 37. Bacardi Carta Blanca White Rum
  {
    name: "Bacardi Carta Blanca White Rum",
    brand: "Bacardi",
    price: 49.99,
    rumStyle: "White",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "Carta Blanca",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in White Oak & Coconut Shell Charcoal Filtered",
    flavourProfile: ["Almond", "Lime Zest", "Vanilla", "Clean Floral"],
    desc: "Created in 1862 by Don Facundo Bacardí Massó. Aged in white oak barrels and charcoal-filtered through coconut shell charcoals for supreme cocktail clarity.",
    shortDesc: "The world's benchmark light white rum; charcoal filtered for crisp Mojitos and Daiquiris.",
    badge: "Global Classic",
    featured: true,
    variants: [
      { size: "700ml", price: 49.99, isDefault: true },
      { size: "1L", price: 64.99, isDefault: false }
    ],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 38. Bacardi Carta Oro Gold Rum
  {
    name: "Bacardi Carta Oro Gold Rum",
    brand: "Bacardi",
    price: 49.99,
    rumStyle: "Gold",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "Carta Oro",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Toasted American Oak Barrels",
    flavourProfile: ["Vanilla", "Butter Caramel", "Toasted Almond", "Sweet Banana"],
    desc: "Expertly crafted in toasted oak barrels and shaped through a secret charcoal blend for rich golden smoothness in Cuba Libres and Rum Punches.",
    shortDesc: "Rich golden rum aged in toasted oak with butter caramel and vanilla notes.",
    badge: "Gold Standard",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 39. Bacardi Carta Negra Dark Rum
  {
    name: "Bacardi Carta Negra Dark Rum",
    brand: "Bacardi",
    price: 49.99,
    rumStyle: "Dark",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "Carta Negra",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured in Heavily Charred Oak Barrels",
    flavourProfile: ["Dark Caramel", "Toasted Oak", "Treacle", "Licorice"],
    desc: "Medium-bodied black rum crafted in heavily charred oak casks and shaped through a select charcoal filtration for bold, smoky molasses intensity.",
    shortDesc: "Heavily charred barrel-aged black rum offering intense dark caramel and smoke.",
    badge: "Dark Rum",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 40. Bacardi Spiced Rum
  {
    name: "Bacardi Spiced Rum",
    brand: "Bacardi",
    price: 49.99,
    rumStyle: "Spiced",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "Spiced Blend",
    abv: "35.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Charred Oak Aged & Infused with Natural Spices",
    flavourProfile: ["Creamy Vanilla", "Cinnamon", "Nutmeg", "Smoky Oak"],
    desc: "Aged in charred American oak and blended with natural vanilla, cinnamon, and nutmeg spices for an ultra-smooth, mixable spiced rum.",
    shortDesc: "Charred oak-aged spiced rum blended with natural vanilla, cinnamon, and nutmeg.",
    badge: "Spiced Spirit",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 41. Bacardi Reserva Ocho 8 Year Old Rum
  {
    name: "Bacardi Reserva Ocho 8 Year Old Rum",
    brand: "Bacardi",
    price: 79.99,
    rumStyle: "Aged",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "8 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged a Minimum 8 Years in American Oak",
    flavourProfile: ["Prune", "Apricot", "Nutmeg", "Vanilla", "Toasted Oak"],
    desc: "Historically reserved exclusively for the Bacardí family. Aged for a minimum of 8 years under the Caribbean sun, offering rich stonefruit and spice.",
    shortDesc: "Minimum 8-year barrel aged reserve rum with prune, apricot, and warm oak spices.",
    badge: "8YO Family Reserve",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 42. Bacardi Gran Reserva Diez 10 Year Old Rum
  {
    name: "Bacardi Gran Reserva Diez 10 Year Old Rum",
    brand: "Bacardi",
    price: 99.99,
    rumStyle: "Aged",
    country: "Puerto Rico",
    state: "",
    region: "Cataño, Caribbean",
    ageStatement: "10 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured 10 Years in White Oak & Charcoal Filtered",
    flavourProfile: ["Caramelised Banana", "Pear", "Vanilla", "Charred Oak"],
    desc: "A masterwork aged for an uninterrupted 10 years in charred white oak casks before final charcoal polish. Luxurious sipping rum.",
    shortDesc: "Masterful 10-year aged Caribbean rum featuring caramelised banana, pear, and toasted oak.",
    badge: "10YO Gran Reserva",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 43. Captain Morgan Original Spiced Gold Rum
  {
    name: "Captain Morgan Original Spiced Gold Rum",
    brand: "Captain Morgan",
    price: 49.99,
    rumStyle: "Spiced",
    country: "Jamaica",
    state: "",
    region: "Caribbean Blend",
    ageStatement: "Spiced Gold",
    abv: "35.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured in Charred White Oak Barrels",
    flavourProfile: ["Vanilla", "Brown Sugar", "Dried Fruit", "Warming Spice"],
    desc: "Captain Morgan Original Spiced Gold blends Caribbean rums with natural vanilla and aromatic spices, aged in charred white oak barrels.",
    shortDesc: "World-famous Caribbean spiced gold rum with smooth vanilla and warming spices.",
    badge: "Party Staple",
    featured: true,
    variants: [
      { size: "700ml", price: 49.99, isDefault: true },
      { size: "1L", price: 64.99, isDefault: false }
    ],
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 44. Captain Morgan Dark Rum
  {
    name: "Captain Morgan Dark Rum",
    brand: "Captain Morgan",
    price: 49.99,
    rumStyle: "Dark",
    country: "Jamaica",
    state: "",
    region: "Caribbean Blend",
    ageStatement: "Dark Reserve",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Double-Charred Black Oak",
    flavourProfile: ["Caramel", "Treacle", "Ripe Banana", "Smoked Wood"],
    desc: "Blended from Jamaican, Guyanese, and Bajan rums and aged in charred oak for a rich, full-bodied dark rum.",
    shortDesc: "Rich Caribbean dark rum aged in charred oak with deep caramel and treacle.",
    badge: "Dark Rum",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 45. Captain Morgan White Rum
  {
    name: "Captain Morgan White Rum",
    brand: "Captain Morgan",
    price: 49.99,
    rumStyle: "White",
    country: "Jamaica",
    state: "",
    region: "Caribbean",
    ageStatement: "White Blend",
    abv: "37.5%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Five Times Distilled & Charcoal Filtered",
    flavourProfile: ["Crisp Cane", "Green Apple", "Coconut", "Pepper"],
    desc: "Five times distilled from Caribbean molasses, offering an exceptionally crisp, clean profile for tropical cocktails and Mojitos.",
    shortDesc: "Five times distilled Caribbean white rum for crisp and refreshing cocktails.",
    badge: "White Rum",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 46. Captain Morgan Sliced Apple Rum
  {
    name: "Captain Morgan Sliced Apple Rum",
    brand: "Captain Morgan",
    price: 54.99,
    rumStyle: "Flavoured",
    country: "Jamaica",
    state: "",
    region: "Caribbean",
    ageStatement: "Flavoured Spirit",
    abv: "25.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Infused with Crisp Apple & Caribbean Spices",
    flavourProfile: ["Crisp Green Apple", "Warm Ginger", "Vanilla", "Brown Sugar"],
    desc: "Original spiced rum infused with crisp juicy sliced apples and warm spices. Delicious over ice or paired with dry ginger beer.",
    shortDesc: "Spiced Caribbean rum infused with crisp green apple and sweet spice.",
    badge: "Sliced Apple",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 47. Kraken Black Spiced Rum
  {
    name: "Kraken Black Spiced Rum",
    brand: "The Kraken",
    price: 59.99,
    rumStyle: "Spiced",
    country: "Trinidad & Tobago",
    state: "",
    region: "Caribbean",
    ageStatement: "Black Spiced",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Infused with 11 Secret Caribbean Spices",
    flavourProfile: ["Vanilla Bean", "Cinnamon", "Clove", "Ginger", "Dark Molasses"],
    desc: "The Kraken is an imported Caribbean black spiced rum enriched with exotic spices including cinnamon, ginger, and clove.",
    shortDesc: "Legendary black spiced Caribbean rum infused with 11 secret warming spices.",
    badge: "Best Seller",
    featured: true,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 48. Kraken Black Roast Coffee Rum
  {
    name: "Kraken Black Roast Coffee Rum",
    brand: "The Kraken",
    price: 59.99,
    rumStyle: "Flavoured",
    country: "Trinidad & Tobago",
    state: "",
    region: "Caribbean",
    ageStatement: "Coffee Infusion",
    abv: "33.3%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Infused with Dark Roast Arabica Coffee",
    flavourProfile: ["Dark Roast Arabica Coffee", "Cinnamon", "Vanilla", "Brown Sugar"],
    desc: "A bold fusion of Caribbean black spiced rum and dark roasted Arabica coffee beans. Delivers rich espresso aromas alongside vanilla and spice.",
    shortDesc: "Black spiced rum infused with rich dark roast Arabica coffee beans.",
    badge: "Roast Coffee",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 49. Kraken Cherry & Madagascan Vanilla Rum
  {
    name: "Kraken Cherry & Madagascan Vanilla Rum",
    brand: "The Kraken",
    price: 59.99,
    rumStyle: "Flavoured",
    country: "Trinidad & Tobago",
    state: "",
    region: "Caribbean",
    ageStatement: "Cherry & Vanilla",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Black Rum Infused with Deep Cherry & Madagascan Vanilla",
    flavourProfile: ["Black Cherry", "Madagascan Vanilla", "Warming Spice", "Cocoa"],
    desc: "Rich Caribbean black spiced rum paired with natural black cherry and bourbon vanilla from Madagascar.",
    shortDesc: "Rich black spiced rum infused with ripe black cherries and fragrant Madagascan vanilla.",
    badge: "Cherry & Vanilla",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 50. Sailor Jerry Spiced Rum
  {
    name: "Sailor Jerry Spiced Rum",
    brand: "Sailor Jerry",
    price: 54.99,
    rumStyle: "Spiced",
    country: "Virgin Islands",
    state: "",
    region: "Caribbean",
    ageStatement: "Navy Spiced 40%",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Oak Aged & Infused with Natural Vanilla and Nutmeg",
    flavourProfile: ["Vanilla", "Nutmeg", "Cinnamon", "Toffee"],
    desc: "Crafted in the authentic tradition of sailor tattoo master Norman 'Sailor Jerry' Collins. Infused with natural vanilla, cinnamon, and nutmeg.",
    shortDesc: "Bold 40% navy-strength spiced rum with rich natural vanilla, cinnamon, and nutmeg.",
    badge: "Navy Spiced",
    featured: true,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 51. Malibu Original Coconut Rum
  {
    name: "Malibu Original Coconut Rum",
    brand: "Malibu",
    price: 44.99,
    rumStyle: "Flavoured",
    country: "Barbados",
    state: "",
    region: "Caribbean",
    ageStatement: "Coconut Liqueur",
    abv: "21.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Caribbean White Rum Blended with Natural Coconut",
    flavourProfile: ["Sweet Coconut", "Vanilla", "Fresh Sugar Cane"],
    desc: "The world’s favourite coconut flavoured Caribbean rum spirit. The sunshine in a bottle essential for Piña Coladas and tropical mixers.",
    shortDesc: "World-famous Caribbean white rum blended with natural sweet coconut extract.",
    badge: "Coconut Classic",
    featured: true,
    variants: [
      { size: "700ml", price: 44.99, isDefault: true },
      { size: "1L", price: 54.99, isDefault: false }
    ],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 52. Malibu Strawberry Rum
  {
    name: "Malibu Strawberry Rum",
    brand: "Malibu",
    price: 44.99,
    rumStyle: "Flavoured",
    country: "Barbados",
    state: "",
    region: "Caribbean",
    ageStatement: "Strawberry Liqueur",
    abv: "21.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Caribbean Rum Infused with Ripe Strawberry & Coconut",
    flavourProfile: ["Sweet Ripe Strawberry", "Coconut Cream", "Vanilla"],
    desc: "Juicy ripe strawberry flavour blended seamlessly with smooth Caribbean white rum and delicate coconut.",
    shortDesc: "Caribbean rum bursting with sweet ripe strawberry and coconut flavours.",
    badge: "Strawberry",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 53. Havana Club 3 Años Rum
  {
    name: "Havana Club 3 Años Rum",
    brand: "Havana Club",
    price: 54.99,
    rumStyle: "White",
    country: "Cuba",
    state: "",
    region: "San José de Las Lajas",
    ageStatement: "3 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged 3 Years in White Oak & Carbon Filtered",
    flavourProfile: ["Smoky Oak", "Vanilla", "Caramelised Pear", "Sugarcane"],
    desc: "The authentic Cuban rum for the classic Mojito and Daiquiri. Aged for three years in white oak barrels in Cuba, lending straw gold colour and woody nuances.",
    shortDesc: "Authentic 3-year aged Cuban rum; the essential base for real Cuban Mojitos.",
    badge: "Cuban Classic",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 54. Havana Club 7 Años Rum
  {
    name: "Havana Club 7 Años Rum",
    brand: "Havana Club",
    price: 69.99,
    rumStyle: "Aged",
    country: "Cuba",
    state: "",
    region: "San José de Las Lajas",
    ageStatement: "7 Years Continuous Aging",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured in Ex-Bourbon White Oak Barrels",
    flavourProfile: ["Cuban Tobacco", "Cedarwood", "Sweet Tropical Fruit", "Dark Cocoa"],
    desc: "Created by legendary Maestro Ronero Don José Navarro. Aged in ex-bourbon white oak barrels in Cuba, offering tobacco, sweet fruits, and dark cocoa.",
    shortDesc: "Iconic 7-year aged Cuban sipping rum with rich notes of Cuban tobacco, cocoa, and cedar.",
    badge: "7YO Añejo",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 55. Havana Club Selección de Maestros Rum
  {
    name: "Havana Club Selección de Maestros Rum",
    brand: "Havana Club",
    price: 99.99,
    rumStyle: "Aged",
    country: "Cuba",
    state: "",
    region: "San José de Las Lajas",
    ageStatement: "Triple Barrel Aged",
    abv: "45.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Finished in Specially Selected Aromatic Oak Casks",
    flavourProfile: ["Pecan Nut", "Spiced Cocoa", "Candied Orange", "Cigar Smoke"],
    desc: "Crafted collectively by the Maestros del Ron Cubano. Finished in specially selected aromatic white oak barrels and bottled straight at 45% ABV.",
    shortDesc: "Prestige triple-barrel aged Cuban rum finished in aromatic oak barrels.",
    badge: "Selección de Maestros",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 56. Appleton Estate Signature Blend Rum
  {
    name: "Appleton Estate Signature Blend Rum",
    brand: "Appleton Estate",
    price: 64.99,
    rumStyle: "Gold",
    country: "Jamaica",
    state: "",
    region: "Nassau Valley",
    ageStatement: "Signature",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Number One Select American Oak Barrels",
    flavourProfile: ["Dried Apricot", "Molasses", "Peach", "Warm Toast"],
    desc: "A delicious blend of pot and column rums, aged in Number One Select American oak barrels. Fresh, fruit-forward, and indispensable for Mai Tais.",
    shortDesc: "Versatile Jamaican rum blend with dried apricot, warm toast, and citrus zest.",
    badge: "Signature Blend",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 57. Appleton Estate 8 Year Old Reserve Rum
  {
    name: "Appleton Estate 8 Year Old Reserve Rum",
    brand: "Appleton Estate",
    price: 79.99,
    rumStyle: "Aged",
    country: "Jamaica",
    state: "",
    region: "Nassau Valley",
    ageStatement: "8 Years Minimum",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Matured a Minimum of 8 Tropical Years in Oak",
    flavourProfile: ["Spiced Apple", "Ginger", "Honeyed Vanilla", "Charred Wood"],
    desc: "Created to celebrate the 250th anniversary of Appleton Estate. Every drop is aged for at least 8 years in Jamaica's tropical heat.",
    shortDesc: "Minimum 8-year aged Jamaican pot-still rum with honey, ginger, and spiced apple.",
    badge: "8YO Reserve",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 58. Appleton Estate 12 Year Old Rare Casks Rum
  {
    name: "Appleton Estate 12 Year Old Rare Casks Rum",
    brand: "Appleton Estate",
    price: 99.99,
    rumStyle: "Aged",
    country: "Jamaica",
    state: "",
    region: "Nassau Valley",
    ageStatement: "12 Years Minimum",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Minimum 12 Years in Charred American Oak",
    flavourProfile: ["Orange Peel", "Dark Hazelnut", "Molasses Funk", "Rich Vanilla Oak"],
    desc: "A true minimum age statement rum from Jamaica's lush Nassau Valley. Matured for at least 12 tropical years in American oak.",
    shortDesc: "Minimum 12 tropical years aged in American oak with hazelnut, orange peel, and Jamaican pot still character.",
    badge: "12YO Rare Casks",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 59. Appleton Estate 15 Year Old Black River Casks Rum
  {
    name: "Appleton Estate 15 Year Old Black River Casks Rum",
    brand: "Appleton Estate",
    price: 149.99,
    rumStyle: "Aged",
    country: "Jamaica",
    state: "",
    region: "Nassau Valley",
    ageStatement: "15 Years Minimum",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "15 Tropical Years Aged in Select Bourbon Barrels",
    flavourProfile: ["Toasted Almond", "Velvety Dark Cocoa", "Candied Ginger", "Orange Marmalade"],
    desc: "Pays homage to the Black River that provides limestone-filtered spring water to the distillery. Aged 15 long tropical years.",
    shortDesc: "Prestige 15-year Jamaican rum aged in select oak barrels with candied ginger and cocoa.",
    badge: "15YO Black River",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 60. Wray & Nephew Overproof White Rum
  {
    name: "Wray & Nephew Overproof White Rum",
    brand: "Wray & Nephew",
    price: 64.99,
    rumStyle: "Overproof",
    country: "Jamaica",
    state: "",
    region: "Kingston / Nassau Valley",
    ageStatement: "Unaged Overproof 63%",
    abv: "63.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Pure Pot Still High-Ester Unaged Rum",
    flavourProfile: ["Overripe Banana", "Pot Still Ester Funk", "Pineapple", "Molasses Warmth"],
    desc: "The heartbeat of Jamaica. Over 90% of all rum consumed in Jamaica is Wray & Nephew Overproof (63% ABV). Packed with intense pot-still ester funk.",
    shortDesc: "Iconic 63% Jamaican overproof rum packed with high-ester tropical fruit funk.",
    badge: "63% Overproof",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 61. Mount Gay Eclipse Rum
  {
    name: "Mount Gay Eclipse Rum",
    brand: "Mount Gay",
    price: 64.99,
    rumStyle: "Gold",
    country: "Barbados",
    state: "",
    region: "St. Lucy",
    ageStatement: "Eclipse Heritage",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Toasted American Whiskey Casks",
    flavourProfile: ["Apricot", "Banana", "Vanilla", "Toasted Oak"],
    desc: "From the world's oldest commercial rum distillery (est. 1703). Distilled from column and copper pot stills and aged in toasted ex-whiskey casks.",
    shortDesc: "The golden standard of Barbados rum with bright fruit, vanilla, and gentle oak notes.",
    badge: "Bajan Classic",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 62. Mount Gay Black Barrel Rum
  {
    name: "Mount Gay Black Barrel Rum",
    brand: "Mount Gay",
    price: 89.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Lucy",
    ageStatement: "Double Cask Blend",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Finished in Deeply Charred Bourbon Casks",
    flavourProfile: ["Wood Smoke", "Ginger", "Pepper", "Rich Toffee", "Vanilla"],
    desc: "Crafted by Master Blender Trudiann Branker. Robust blend of pot and column rums finished in deeply charred bourbon casks for bold smoky depth.",
    shortDesc: "Double-cask Bajan rum finished in heavily charred bourbon oak with wood smoke and spice.",
    badge: "Black Barrel",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 63. Mount Gay XO Triple Cask Blend Rum
  {
    name: "Mount Gay XO Triple Cask Blend Rum",
    brand: "Mount Gay",
    price: 109.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Lucy",
    ageStatement: "5-17 Years Blend",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "American Whiskey, Bourbon & Cognac Cask Maturation",
    flavourProfile: ["Salted Caramel", "Baked Fig", "Dark Chocolate", "Clove Oak"],
    desc: "Triple Cask Blend combines pot and column still rums aged 5 to 17 years in American whiskey, bourbon, and Cognac casks.",
    shortDesc: "Triple cask Barbados rum aged 5–17 years in whiskey, bourbon, and Cognac barrels.",
    badge: "XO Triple Cask",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 64. Mount Gay 1703 Master Select Rum
  {
    name: "Mount Gay 1703 Master Select Rum",
    brand: "Mount Gay",
    price: 199.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Lucy",
    ageStatement: "10-30 Years Reserve",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Ultra-Aged American Oak Reserve Casks",
    flavourProfile: ["Roasted Coffee", "Dark Chocolate", "Dried Cherry", "Leather", "Clove"],
    desc: "Celebrates the founding year of Mount Gay (1703). Comprises rare reserve rums aged between 10 and 30 years selected personally by the Master Blender.",
    shortDesc: "Ultra-prestige Bajan rum blending rare reserve barrels aged 10 to 30 years.",
    badge: "1703 Master Select",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 65. Diplomatico Mantuano Rum
  {
    name: "Diplomatico Mantuano Rum",
    brand: "Diplomático",
    price: 69.99,
    rumStyle: "Aged",
    country: "Venezuela",
    state: "",
    region: "La Miel, Lara State",
    ageStatement: "Up to 8 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in White Oak, Ex-Bourbon & Malt Whisky Casks",
    flavourProfile: ["Dried Plums", "Oak Wood", "Vanilla", "Delicate Spice"],
    desc: "An authentic blend of column, batch kettle, and pot still rums aged up to 8 years in white oak barrels. Ideal for sipping and craft rum cocktails.",
    shortDesc: "Versatile Venezuelan rum aged up to 8 years with dried plum and toasted oak.",
    badge: "Mantuano",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 66. Diplomatico Reserva Exclusiva Rum
  {
    name: "Diplomatico Reserva Exclusiva Rum",
    brand: "Diplomático",
    price: 89.99,
    rumStyle: "Aged",
    country: "Venezuela",
    state: "",
    region: "La Miel, Lara State",
    ageStatement: "Up to 12 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Copper Pot Still Aged up to 12 Years in Small Oak Casks",
    flavourProfile: ["Maple Syrup", "Orange Peel", "Brown Sugar", "Dark Toffee", "Cocoa"],
    desc: "Composed of 80% heavy copper pot still rums aged for up to 12 years in small oak casks. Remarkable elegance, rich maple syrup sweetness, and orange peel.",
    shortDesc: "Super-premium Venezuelan sipping rum aged up to 12 years with maple, toffee, and cocoa.",
    badge: "Collector Icon",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 67. Diplomatico Selección de Familia Rum
  {
    name: "Diplomatico Selección de Familia Rum",
    brand: "Diplomático",
    price: 129.99,
    rumStyle: "Aged",
    country: "Venezuela",
    state: "",
    region: "La Miel, Lara State",
    ageStatement: "Up to 12 Years",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "American White Oak Bourbon & Spanish Sherry Casks",
    flavourProfile: ["Red Fruits", "Dark Plum", "Charred Oak", "Caramel Toffee"],
    desc: "Created by Diplomático's Maestros Roneros alongside the Ballesteros family. Finished in ex-Sherry casks for deeper dryness and plum complexity.",
    shortDesc: "Master blender reserve finished in Spanish sherry casks with plum, oak, and dark toffee.",
    badge: "Prestige Reserve",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 68. Diplomatico Ambassador Rum
  {
    name: "Diplomatico Ambassador Rum",
    brand: "Diplomático",
    price: 399.99,
    rumStyle: "Aged",
    country: "Venezuela",
    state: "",
    region: "La Miel, Lara State",
    ageStatement: "12+ Years & Pedro Ximénez Finish",
    abv: "47.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged 12 Years in White Oak & 2 Years in Pedro Ximénez Sherry Casks",
    flavourProfile: ["Port Wine", "Cigar Box", "Dark Raisin", "Rich Nutmeg", "Smoked Toffee"],
    desc: "The crowning achievement of Diplomático. 100% pot still rum aged 12 years in white oak, then finished for two years in Spanish Pedro Ximénez sherry butts. Bottled uncut at 47% ABV.",
    shortDesc: "Ultra-luxury 100% pot still rum finished in Pedro Ximénez sherry butts at 47% ABV.",
    badge: "Ambassador Vault",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 69. Plantation 3 Stars White Rum
  {
    name: "Plantation 3 Stars White Rum",
    brand: "Plantation (Planteray)",
    price: 59.99,
    rumStyle: "White",
    country: "Barbados, Jamaica & Trinidad",
    state: "",
    region: "Caribbean Blend",
    ageStatement: "3 Stars Blend",
    abv: "41.2%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged Caribbean Rums Carbon Filtered",
    flavourProfile: ["Biscuit", "Cane Juice", "Delicate Floral", "White Pepper"],
    desc: "A tribute to the historic rums of the Caribbean: Barbados unaged, Trinidad 2-3 year aged, and Jamaica pot still rum, carbon-filtered for clear Mojitos and Daiquiris.",
    shortDesc: "Bartender-revered Caribbean white rum blend with biscuit and floral cane notes.",
    badge: "3 Stars",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 70. Plantation Original Dark Rum
  {
    name: "Plantation Original Dark Rum",
    brand: "Plantation (Planteray)",
    price: 59.99,
    rumStyle: "Dark",
    country: "Barbados & Jamaica",
    state: "",
    region: "Caribbean Blend / Cognac, France",
    ageStatement: "Original Dark",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Tropical Bourbon Cask & French Ferrand Oak Casks",
    flavourProfile: ["Plum", "Banana", "Spiced Toffee", "Smoked Molasses"],
    desc: "Rich blend of pot still Jamaican rum and column still Barbados rum, matured in the tropics before finishing in French oak casks in southwestern France.",
    shortDesc: "Rich double-aged Caribbean blend finished in French oak casks.",
    badge: "Original Dark",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 71. Plantation XO 20th Anniversary Rum
  {
    name: "Plantation XO 20th Anniversary Rum",
    brand: "Plantation (Planteray)",
    price: 99.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "Caribbean / Cognac, France",
    ageStatement: "XO 20th Anniversary",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Tropical Bourbon Casks & French Ferrand Cognac Casks",
    flavourProfile: ["Coconut Cream", "Candied Orange", "Vanilla Pod", "Milk Chocolate", "Toasted Oak"],
    desc: "Aged for many years in bourbon casks in Barbados, then shipped across the Atlantic to the Ferrand estate in Cognac for further maturation in small French oak casks.",
    shortDesc: "Double-aged in Barbados bourbon barrels and French Cognac casks with coconut and milk chocolate.",
    badge: "XO 20th Anniv",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 72. Plantation Barbados 5 Year Old Rum
  {
    name: "Plantation Barbados 5 Year Old Rum",
    brand: "Plantation (Planteray)",
    price: 69.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "Caribbean / Cognac, France",
    ageStatement: "5 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "3-4 Years Bourbon in Barbados + 1-2 Years Ferrand Cognac Oak",
    flavourProfile: ["Roasted Coconut", "Grilled Pineapple", "Vanilla Cream", "Light Nutmeg"],
    desc: "Matured 3 to 4 years in bourbon barrels in Barbados, then finished for 1 to 2 years in French oak casks at Château de Bonbonnet in Cognac.",
    shortDesc: "Double-aged Bajan rum with grilled pineapple, roasted coconut, and vanilla cream.",
    badge: "Barbados 5YO",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 73. Plantation OFTD Overproof Rum
  {
    name: "Plantation OFTD Overproof Rum",
    brand: "Plantation (Planteray)",
    price: 79.99,
    rumStyle: "Overproof",
    country: "Barbados, Jamaica & Guyana",
    state: "",
    region: "Caribbean Blend",
    ageStatement: "Overproof 69%",
    abv: "69.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "High-Ester Pot & Column Blend in Oak Casks",
    flavourProfile: ["Coffee Beans", "Cacao", "Molasses", "Prune", "Wood Smoke"],
    desc: "Created by Alexandre Gabriel alongside rum luminaries. Bottled at 69% ABV, blending rums from Barbados, Guyana, and Jamaica. Essential for Tiki cocktails.",
    shortDesc: "Colossal 69% ABV overproof rum blend from Barbados, Jamaica, and Guyana.",
    badge: "69% Overproof",
    featured: false,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  },
  // 74. Flor de Caña 4 Year Old Extra Seco Rum
  {
    name: "Flor de Caña 4 Year Old Extra Seco Rum",
    brand: "Flor de Caña",
    price: 59.99,
    rumStyle: "White",
    country: "Nicaragua",
    state: "",
    region: "Chichigalpa",
    ageStatement: "4 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Naturally Aged 4 Years in Small Bourbon Barrels",
    flavourProfile: ["Almond", "Vanilla", "Crisp Coconut", "Smooth Wood"],
    desc: "Sustainably produced and naturally aged for 4 years at the base of the active San Cristóbal volcano in Nicaragua. Carbon Neutral and Fair Trade certified.",
    shortDesc: "Naturally aged 4-year white rum from Nicaragua; zero sugar, Fair Trade certified.",
    badge: "Carbon Neutral",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 75. Flor de Caña 7 Year Old Gran Reserva Rum
  {
    name: "Flor de Caña 7 Year Old Gran Reserva Rum",
    brand: "Flor de Caña",
    price: 69.99,
    rumStyle: "Aged",
    country: "Nicaragua",
    state: "",
    region: "Chichigalpa",
    ageStatement: "7 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Naturally Aged 7 Years in Charred Bourbon Casks",
    flavourProfile: ["Roasted Nut", "Toasted Oak", "Dark Honey", "Baked Apple"],
    desc: "Mahogany-hued 7-year naturally aged rum from single estate Nicaraguan sugarcane. Full-bodied with dark honey and roasted coconut.",
    shortDesc: "7-year naturally aged volcanic rum with roasted nuts and dark honey.",
    badge: "7YO Gran Reserva",
    featured: false,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 76. Flor de Caña 12 Year Old Rum
  {
    name: "Flor de Caña 12 Year Old Rum",
    brand: "Flor de Caña",
    price: 89.99,
    rumStyle: "Aged",
    country: "Nicaragua",
    state: "",
    region: "Chichigalpa",
    ageStatement: "12 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Naturally Aged 12 Years in Small Bourbon Barrels",
    flavourProfile: ["Red Apple", "Buttered Toffee", "Toasted Hazelnut", "Vanilla"],
    desc: "Naturally aged for 12 years in small bourbon barrels at the base of the active San Cristóbal volcano in Nicaragua. Zero added sugar.",
    shortDesc: "Naturally aged 12 years at the base of an active volcano; zero added sugar, Fair Trade certified.",
    badge: "12YO Centenario",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 77. Flor de Caña 18 Year Old Rum
  {
    name: "Flor de Caña 18 Year Old Rum",
    brand: "Flor de Caña",
    price: 149.99,
    rumStyle: "Aged",
    country: "Nicaragua",
    state: "",
    region: "Chichigalpa",
    ageStatement: "18 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "18 Years Naturally Matured in American Oak",
    flavourProfile: ["Dark Cocoa", "Roasted Almonds", "Oak Spice", "Dried Fig"],
    desc: "An extraordinary 18-year naturally aged rum from the Flor de Caña single estate. Matured without artificial additives or accelerants for nearly two decades.",
    shortDesc: "Estate-grown volcanic rum aged naturally for 18 years with rich cocoa and spiced oak.",
    badge: "18YO Prestige",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 78. Bumbu Original Rum
  {
    name: "Bumbu Original Rum",
    brand: "Bumbu",
    price: 69.99,
    rumStyle: "Spiced",
    country: "Barbados",
    state: "",
    region: "Pan-Caribbean Blend",
    ageStatement: "Craft Blend up to 15 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in First-Fill American Bourbon Casks",
    flavourProfile: ["Madagascan Vanilla", "Soft Caramel", "Toasted Oak", "Roasted Banana"],
    desc: "Distilled from sugarcane sourced across 8 different Caribbean countries and aged up to 15 years in bourbon barrels in Barbados. Infused with natural spices.",
    shortDesc: "Artisanal Caribbean rum aged up to 15 years with vanilla, soft caramel, and toasted oak.",
    badge: "Craft Icon",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 79. Bumbu XO Rum
  {
    name: "Bumbu XO Rum",
    brand: "Bumbu",
    price: 89.99,
    rumStyle: "Aged",
    country: "Panama",
    state: "",
    region: "Pesé",
    ageStatement: "Aged up to 18 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Bourbon Barrels & Finished in Spanish White Oak Sherry Butts",
    flavourProfile: ["Toffee", "Toasted Oak", "Vanilla", "Orange Zest", "Spiced Pepper"],
    desc: "Distilled in Panama in copper pot stills and aged up to 18 years in American bourbon barrels before selective finishing in Andalusian white oak sherry butts.",
    shortDesc: "Panamanian rum aged up to 18 years and finished in Spanish sherry casks.",
    badge: "Bumbu XO",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 80. Ron Zacapa 23 Solera Gran Reserva Rum
  {
    name: "Ron Zacapa 23 Solera Gran Reserva Rum",
    brand: "Ron Zacapa",
    price: 109.99,
    rumStyle: "Aged",
    country: "Guatemala",
    state: "",
    region: "Quetzaltenango (2,300m)",
    ageStatement: "Solera 6-23 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Sistema Solera in Bourbon, Sherry & Pedro Ximénez Casks",
    flavourProfile: ["Honeycomb", "Sweet Sherry", "Roasted Hazelnut", "Dark Chocolate", "Vanilla"],
    desc: "Crafted in the Guatemalan highlands at 2,300 metres above sea level using virgin sugar cane honey. Aged in a Sistema Solera in ex-whiskey, sherry, and PX wine barrels.",
    shortDesc: "Aged above the clouds in Guatemala in Pedro Ximenez and sherry casks (6–23 years).",
    badge: "Solera 23",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 81. Ron Zacapa XO Rum
  {
    name: "Ron Zacapa XO Rum",
    brand: "Ron Zacapa",
    price: 249.99,
    rumStyle: "Aged",
    country: "Guatemala",
    state: "",
    region: "Quetzaltenango (2,300m)",
    ageStatement: "Solera 6-25 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Solera Aged & Finished in French Cognac Casks",
    flavourProfile: ["Black Cherry", "Dark Chocolate", "Toasted Almond", "Cognac Oak Spice"],
    desc: "A blend of reserve rums aged between 6 and 25 years, finished in French oak barrels previously used to mature fine Cognac. Presented in a luxury decanter.",
    shortDesc: "Ultra-luxury solera rum finished in French Cognac casks with black cherry and cocoa.",
    badge: "Zacapa XO",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 82. El Dorado 12 Year Old Rum
  {
    name: "El Dorado 12 Year Old Rum",
    brand: "El Dorado",
    price: 89.99,
    rumStyle: "Aged",
    country: "Guyana",
    state: "",
    region: "Demerara River",
    ageStatement: "12 Years Minimum",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Historic Enmore & Diamond Wooden Stills Aged in Oak",
    flavourProfile: ["Tropical Fruits", "Nutmeg", "Smoky Molasses", "Dark Honey", "Toffee"],
    desc: "Distilled along the banks of Guyana's Demerara River using the world's last operational historic wooden Enmore and Port Mourant pot stills. Matured a minimum of 12 years.",
    shortDesc: "Historic wooden pot-still Demerara rum aged 12 years with deep honey and toffee.",
    badge: "Demerara 12YO",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 83. El Dorado 15 Year Old Rum
  {
    name: "El Dorado 15 Year Old Rum",
    brand: "El Dorado",
    price: 129.99,
    rumStyle: "Aged",
    country: "Guyana",
    state: "",
    region: "Demerara River",
    ageStatement: "15 Years Minimum",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Historic Wooden Coffey & Pot Still Oak Maturation",
    flavourProfile: ["Dark Chocolate", "Candied Orange Peel", "Black Pepper", "Roasted Walnut", "Molasses"],
    desc: "A minimum 15-year blend combining spirits from the historic wooden Coffey still and double wooden pot stills of Guyana. Renowned by critics worldwide.",
    shortDesc: "Critically acclaimed 15-year Demerara rum with rich dark chocolate, roasted walnut, and orange peel.",
    badge: "Demerara 15YO",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 84. El Dorado 21 Year Old Rum
  {
    name: "El Dorado 21 Year Old Rum",
    brand: "El Dorado",
    price: 199.99,
    rumStyle: "Aged",
    country: "Guyana",
    state: "",
    region: "Demerara River",
    ageStatement: "21 Years Minimum",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "21 Tropical Years in Hand-Selected Oak Casks",
    flavourProfile: ["Mocha", "Cigar Tobacco", "Dried Dark Plum", "Rich Leather", "Demerara Sugar"],
    desc: "A triumph of patience. Minimum 21 tropical years of oak maturation along the equator in Guyana. Viscous, opulent, and breathtakingly complex.",
    shortDesc: "Rare 21-year minimum aged Demerara rum with mocha, cigar tobacco, and deep leather.",
    badge: "Demerara 21YO",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 85. Doorly’s 5 Year Old Rum
  {
    name: "Doorly’s 5 Year Old Rum",
    brand: "Doorly's",
    price: 69.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Philip / Foursquare",
    ageStatement: "5 Years",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged 5 Years in Charred American Oak at Foursquare",
    flavourProfile: ["Toasted Coconut", "Warm Oak", "Vanilla", "Brown Sugar"],
    desc: "Distilled at the acclaimed Foursquare Distillery in Barbados under Master Distiller Richard Seale. Aged 5 tropical years with zero added sugars.",
    shortDesc: "Foursquare-distilled 5-year Bajan rum with toasted coconut, vanilla, and pure oak.",
    badge: "Foursquare Distilled",
    featured: true,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop"
  },
  // 86. Doorly’s XO Rum
  {
    name: "Doorly’s XO Rum",
    brand: "Doorly's",
    price: 89.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Philip / Foursquare",
    ageStatement: "XO Cask Blend",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Ex-Bourbon & Finished in Oloroso Sherry Casks",
    flavourProfile: ["Sherried Raisins", "Dark Chocolate", "Vanilla", "Toasted Hazelnut"],
    desc: "Distilled at Foursquare in Barbados. Matured in bourbon barrels before a delicate secondary finish in Spanish Oloroso sherry casks.",
    shortDesc: "Foursquare rum finished in Oloroso sherry casks with rich raisin and hazelnut complexity.",
    badge: "Oloroso Finish",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 87. Doorly’s 12 Year Old Rum
  {
    name: "Doorly’s 12 Year Old Rum",
    brand: "Doorly's",
    price: 109.99,
    rumStyle: "Aged",
    country: "Barbados",
    state: "",
    region: "St. Philip / Foursquare",
    ageStatement: "12 Years",
    abv: "43.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged 12 Years in Ex-Bourbon & Madeira Casks",
    flavourProfile: ["Baked Apple", "Madeira Wine", "Toffee", "Charred Oak", "Nutmeg"],
    desc: "A blend of pot and column distillates aged a minimum of 12 years in American bourbon barrels and Portuguese Madeira wine casks.",
    shortDesc: "Masterpiece 12-year rum aged in bourbon and Madeira wine casks by Foursquare.",
    badge: "12YO Madeira Cask",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 88. Foursquare 2009 Rum
  {
    name: "Foursquare 2009 Rum",
    brand: "Foursquare",
    price: 199.99,
    rumStyle: "Cask Strength",
    country: "Barbados",
    state: "",
    region: "St. Philip",
    ageStatement: "12 Years (2009 Vintage)",
    abv: "60.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "12 Tropical Years in Ex-Bourbon Barrels Bottled at 60% ABV",
    flavourProfile: ["Ripe Banana", "Roasted Hazelnut", "Intense Toffee", "Bourbon Oak Tannin"],
    desc: "Mark XIII of the world-renowned Exceptional Cask Selection. Distilled in 2009 and aged for 12 tropical years in Barbados in ex-bourbon barrels. Bottled at 60% cask strength.",
    shortDesc: "Benchmark 2009 vintage cask-strength 60% rum from legendary Master Distiller Richard Seale.",
    badge: "2009 Vintage",
    featured: true,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 89. Foursquare Exceptional Cask Selection Rum
  {
    name: "Foursquare Exceptional Cask Selection Rum",
    brand: "Foursquare",
    price: 199.99,
    rumStyle: "Cask Strength",
    country: "Barbados",
    state: "",
    region: "St. Philip",
    ageStatement: "Exceptional Cask",
    abv: "60.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Dual Bourbon & Port / Sherry Cask Maturation",
    flavourProfile: ["Dark Fruit Compote", "Tobacco Leaf", "Dark Cocoa", "Spiced Oak"],
    desc: "Hailed as the 'Pappy Van Winkle of Rum'. Hand-selected dual-maturation cask strength release uncoloured and unchillfiltered.",
    shortDesc: "World-renowned Exceptional Cask Selection dual-maturation release from Foursquare Barbados.",
    badge: "Exceptional Cask",
    featured: false,
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop"
  },
  // 90. Goslings Black Seal Rum
  {
    name: "Goslings Black Seal Rum",
    brand: "Goslings",
    price: 59.99,
    rumStyle: "Dark",
    country: "Bermuda",
    state: "",
    region: "Hamilton",
    ageStatement: "Black Seal",
    abv: "40.0%",
    size: "700ml",
    containerType: "Bottle",
    caskMaturation: "Aged in Charred American Oak Barrels",
    flavourProfile: ["Stewed Plum", "Molasses", "Charred Oak", "Butterscotch"],
    desc: "The authentic foundation of Bermuda's national cocktail, the Dark 'n Stormy®. Aged in charred American oak barrels for an extraordinarily rich, unctuous molasses profile.",
    shortDesc: "The original Bermuda black rum; essential for an authentic Dark 'n Stormy®.",
    badge: "Dark 'n Stormy®",
    featured: true,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?q=80&w=800&auto=format&fit=crop"
  }
];
